import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'am';
type Theme = 'light' | 'dark';

interface AppContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  theme: Theme;
  toggleTheme: () => void;
  t: (key: string, fallback?: string) => string;
  openPartnerForm: (type: 'doctor' | 'hospital' | 'clinic' | 'api') => void;
  partnerFormToOpen: 'doctor' | 'hospital' | 'clinic' | 'api' | null;
  setPartnerFormToOpen: (type: 'doctor' | 'hospital' | 'clinic' | 'api' | null) => void;
  cart: CartItem[];
  addToCart: (item: CartItem) => void;
  removeFromCart: (id: string) => void;
  clearCart: () => void;
}

export interface CartItem {
  id: string;
  name: string;
  price: number;
  quantity: number;
  dosage?: string;
  form?: string;
}

const translations = {
  en: {
    'auth.login': 'Sign In',
    'auth.signup': 'Sign Up',
    'auth.logout': 'Sign Out',
    welcomeToMedLink: 'Welcome to MedLink Ethiopia',
    welcomeBack: 'Welcome back',
    guestWelcome: 'Welcome to MedLink Ethiopia',
    guestSubtitle: 'Join us to manage your appointments and health records.',
    loginToView: 'Log in to view your data',
    ourServices: 'Our Healthcare Services',
    servicesSubtitle: 'MedLink provides a comprehensive suite of digital healthcare tools to make your medical journey seamless and efficient.',
    findDoctorDesc: 'Search for top specialists across Ethiopia by specialty, hospital, or rating.',
    bookAppointmentDesc: 'Schedule your visits instantly with real-time availability from leading hospitals.',
    emergencyDesc: 'Find the nearest emergency room and get immediate assistance when every second counts.',
    labResultsDesc: 'Access and track your diagnostic reports securely from anywhere, anytime.',
    featuredHospitals: 'Featured Hospitals',
    hospitalsSubtitle: 'Partnering with the most prestigious medical institutions in the country.',
    viewAllHospitals: 'View All Hospitals',
    howMedLinkWorks: 'How MedLink Works',
    step1Title: 'Create Your Profile',
    step1Desc: 'Sign up and securely store your medical history and preferences.',
    step2Title: 'Find & Book',
    step2Desc: 'Search for specialists and book appointments at your convenience.',
    step3Title: 'Get Care',
    step3Desc: 'Visit the hospital and receive world-class medical attention.',
    step4Title: 'Track Results',
    step4Desc: 'Access your prescriptions and lab results directly on your dashboard.',
    healthTipTitle: 'Daily Health Tip',
    healthTipBody: 'Stay hydrated! Drinking at least 8 glasses of water a day helps maintain your energy levels and supports overall organ function.',
    'tips.1.title': 'Hydration',
    'tips.1.body': 'Drink at least 8 glasses of water daily to keep your body functioning optimally.',
    'tips.2.title': 'Quality Sleep',
    'tips.2.body': 'Aim for 7-9 hours of quality sleep each night to allow your body to repair and recharge.',
    'tips.3.title': 'Regular Exercise',
    'tips.3.body': 'Just 30 minutes of moderate activity like brisk walking can significantly improve heart health.',
    'tips.4.title': 'Balanced Diet',
    'tips.4.body': 'Incorporate more colorful vegetables into your meals for a wider range of essential vitamins.',
    'tips.5.title': 'Mental Wellness',
    'tips.5.body': 'Practice mindfulness or meditation for 10 minutes a day to reduce stress and improve focus.',
    'tips.6.title': 'Better Posture',
    'tips.6.body': 'Take regular breaks from your screen and stretch to prevent neck and back strain.',
    'tips.7.title': 'Hand Hygiene',
    'tips.7.body': 'Wash your hands frequently, especially before meals, to prevent the spread of germs.',
    today: 'Today',
    learnMore: 'Learn More',
    loginToAccessRecords: 'Sign in to access your medical records and appointments.',
    bookAppointmentNow: 'Book an Appointment Now',
    bookingDescription: 'Connect with the best doctors and hospitals in Ethiopia. Sign in to schedule your visit and manage your healthcare journey.',
    emergencyCare: 'Emergency Care',
    needEmergencyCare: 'Need Emergency Care?',
    emergencySubtitle: 'Available 24/7 for urgent medical needs.',
    'emergency.available247': 'Available 24/7',
    dashboard: 'Dashboard',
    hello: 'Hello',
    welcome: "Welcome to your health dashboard. Here's what's happening today.",
    upcoming: 'Upcoming',
    prescriptions: 'Prescriptions',
    labResults: 'Lab Results',
    notifications: 'Notifications',
    upcomingAppointments: 'Upcoming Appointments',
    recentLabResults: 'Recent Lab Results',
    viewAll: 'View All',
    noAppointments: 'No upcoming appointments found.',
    noLabResults: 'No lab results available yet.',
    noPrescriptions: 'No active prescriptions.',
    bookFirstVisit: 'Book your first visit',
    activePrescriptions: 'Active Prescriptions',
    quickActions: 'Quick Actions',
    findDoctor: 'Find Doctor',
    emergency: 'Emergency',
    hospitals: 'Hospitals',
    profile: 'Profile',
    appointmentDetails: 'Appointment Details',
    cancelAppointment: 'Cancel Appointment',
    confirmCancel: 'Are you sure you want to cancel this appointment?',
    yes: 'Yes',
    no: 'No',
    close: 'Close',
    patient: 'Patient',
    age: 'Age',
    doctor: 'Doctor',
    specialty: 'Specialty',
    hospital: 'Hospital',
    dateTime: 'Date & Time',
    message: 'Message',
    notes: 'Notes',
    medication: 'Medication',
    dosage: 'Dosage',
    instructions: 'Instructions',
    prescribedOn: 'Prescribed on',
    testName: 'Test Name',
    result: 'Result',
    status: 'Status',
    performedAt: 'Performed at',
    on: 'on',
    notificationPermission: 'Would you like to receive daily health notifications?',
    allow: 'Allow',
    deny: 'Deny',
    notificationTitle: 'Daily Health Reminder',
    notificationBody: 'Check your upcoming appointments and prescriptions for today.',
    'nav.home': 'Home',
    'nav.hospitals': 'Hospitals',
    'nav.doctors': 'Doctors',
    'nav.labs': 'Labs & Diagnostics',
    'nav.pharmacy': 'Pharmacy',
    'nav.emergency': 'Emergency',
    'nav.profile': 'Profile',
    'nav.dashboard': 'Dashboard',
    'common.search': 'Search',
    'common.viewProfile': 'View Profile',
    'common.consultNow': 'Consult Now',
    'common.bookAppointment': 'Book Appointment',
    'common.specialties': 'Specialties',
    'common.topDoctors': 'Top Doctors',
    'common.allSpecialties': 'All Specialties',
    'common.searchPlaceholder': 'Search doctors by name, hospital, or expertise...',
    'common.clearFilters': 'Clear Filters & Search',
    'common.noDoctorsFound': 'No doctors found matching your search.',
    'common.professionalSummary': 'Professional Summary',
    'common.affiliatedHospitals': 'Affiliated Hospitals',
    'common.availableTimes': 'Available Times',
    'common.bookConsultation': 'Book Consultation',
    'common.rating': 'Rating',
    'common.experience': 'Exp.',
    'common.years': 'Yrs',
    'common.specialists': 'Specialists',
    'common.comprehensiveCare': 'Comprehensive Medical Care',
    'common.connectWithSpecialists': 'Connect with specialists across various medical fields for expert consultation and treatment.',
    'common.searchResults': 'Search Results',
    'common.found': 'Found',
    'common.doctorsMatching': 'doctors matching',
    'common.viewAll': 'View All',
    'common.doctors': 'Doctors',
    'common.noDoctorsSpecialty': 'No doctors found for this specialty at the moment.',
    'common.more': 'more',
    'common.facility': 'Facility',
    'common.verified': 'Verified',
    'common.open': 'Open',
    'common.open247': 'Open 24/7',
    'common.generalSpecialist': 'General Specialist',
    'common.booking': 'Booking',
    'hero.headline': 'Connecting Ethiopia to Modern Healthcare',
    'hero.subheadline': 'Advanced Diagnostics • Trusted Specialists • Compassionate Patient Care',
    'dashboard.portal': 'Dashboard / Patient Portal',
    'dashboard.guestPrompt': 'Welcome to MedLink Ethiopia Dashboard – Access your appointments, test results, and care plans. Please log in to continue.',
    'leadingMedicalService': 'Leading Online Medical Service in Ethiopia',
    'whyChooseUs': 'Why Choose MedLink?',
    'whyChooseUsSubtitle': 'We are committed to providing the highest quality healthcare services through innovation and compassion.',
    'reason1Title': 'Expert Specialists',
    'reason1Desc': 'Access a network of highly qualified and experienced medical professionals across all specialties.',
    'reason2Title': 'Seamless Booking',
    'reason2Desc': 'Book appointments instantly with real-time availability, saving you time and effort.',
    'reason3Title': 'Secure Records',
    'reason3Desc': 'Your medical history and test results are stored securely and accessible only by you.',
    'ourMission': 'Our Mission',
    'ourMissionDesc': 'To revolutionize healthcare access in Ethiopia by bridging the gap between patients and providers through cutting-edge digital solutions.',
    'newsUpdates': 'News & Updates',
    'newsUpdatesSubtitle': 'Stay informed about the latest healthcare developments and MedLink features.',
    'news1Title': 'MedLink Expands to Regional Cities',
    'news1Date': 'March 20, 2026',
    'news1Desc': 'We are excited to announce our expansion to Bahir Dar and Hawassa, bringing modern healthcare closer to you.',
    'news2Title': 'New Telemedicine Feature Launched',
    'news2Date': 'March 15, 2026',
    'news2Desc': 'Consult with your doctor from the comfort of your home with our new integrated video consultation tool.',
    'hospitals.title': 'Top Rated Hospitals',
    'hospitals.subtitle': 'Find the best medical facilities near you with expert care and modern technology.',
    'hospitals.searchPlaceholder': 'Search hospitals by name, location, or specialty...',
    'hospitals.allCategories': 'All Categories',
    'hospitals.public': 'Public',
    'hospitals.private': 'Private',
    'hospitals.general': 'General',
    'hospitals.specialized': 'Specialized',
    'hospitals.maternity': 'Maternity',
    'hospitals.children': 'Children',
    'hospitals.emergency': 'Emergency',
    'hospitals.noHospitals': 'No hospitals found matching your criteria.',
    'hospitals.viewDetails': 'View Details',
    'hospitals.bookVisit': 'Book Visit',
    'hospitals.about': 'About',
    'hospitals.services': 'Services',
    'hospitals.location': 'Location',
    'hospitals.contact': 'Contact',
    'hospitals.website': 'Website',
    'hospitals.openNow': 'Open Now',
    'hospitals.closed': 'Closed',
    'hospitals.beds': 'Beds',
    'hospitals.staff': 'Staff',
    'hospitals.emergency247': '24/7 Emergency',
    'hospitals.icu': 'ICU Available',
    'hospitals.pharmacy': 'Pharmacy',
    'hospitals.lab': 'Laboratory',
    'hospitals.radiology': 'Radiology',
    'hospitals.ambulance': 'Ambulance',
    'hospitals.insurance': 'Insurance Accepted',
    'hospitals.parking': 'Parking Available',
    'hospitals.wifi': 'Free WiFi',
    'hospitals.cafeteria': 'Cafeteria',
    'hospitals.bloodBank': 'Blood Bank',
    'hospitals.dialysis': 'Dialysis Center',
    'profile.title': 'Your Profile',
    'profile.subtitle': 'Manage your account settings and personal information.',
    'profile.displayName': 'Display Name',
    'profile.email': 'Email Address',
    'profile.emailNote': 'Email cannot be changed.',
    'profile.saveChanges': 'Save Changes',
    'profile.accountDetails': 'Account Details',
    'profile.memberSince': 'Member Since',
    'profile.accountStatus': 'Account Status',
    'profile.verified': 'Verified',
    'profile.signOut': 'Sign Out of Account',
    'profile.updateSuccess': 'Profile updated successfully!',
    'profile.updateError': 'Error updating profile',
    'profile.placeholderName': 'Your full name',
    'labs.title': 'Laboratory Services',
    'labs.subtitle': 'Access your test results and find nearby diagnostic centers.',
    'labs.searchPlaceholder': 'Search tests or centers...',
    'labs.recentResults': 'Recent Results',
    'labs.findCenter': 'Find a Lab Center',
    'labs.bookTest': 'Book a Test',
    'labs.noResults': 'No lab results available yet.',
    'labs.viewReport': 'View Report',
    'labs.testName': 'Test Name',
    'labs.center': 'Center',
    'labs.result': 'Result',
    'labs.status': 'Status',
    'labs.date': 'Date',
    'labs.imaging': 'Imaging',
    'labs.laboratory': 'Laboratory',
    'labs.radiology': 'Radiology',
    'labs.general': 'General',
    'labs.pharmacy': 'Pharmacy',
    'emergency.title': 'Emergency Services',
    'emergency.subtitle': 'Immediate assistance and critical care information.',
    'emergency.callNow': 'Call Emergency Now',
    'emergency.nearbyER': 'Nearby Emergency Rooms',
    'emergency.firstAid': 'First Aid Guide',
    'emergency.ambulance': 'Request Ambulance',
    'emergency.location': 'Your Location',
    'emergency.sharingLocation': 'Sharing location for faster response...',
    'labs.medStoreTitle': 'Order Medicines Online',
    'labs.medStoreSubtitle': 'Find nearby pharmacies, check medicine availability, and get doorstep delivery.',
    'labs.medStoreFeature1': 'Search by prescription',
    'labs.medStoreFeature2': 'Check medicine availability',
    'labs.medStoreFeature3': 'Home delivery in Addis Ababa',
    'labs.medStoreFeature4': 'Verified pharmacies only',
    'labs.openMedStore': 'Open MedStore',
    'emergency.response': 'Emergency Response',
    'emergency.urgentTitle': 'Need Urgent Medical Assistance?',
    'emergency.urgentSubtitle': 'Our 24/7 emergency dispatch is ready to help. Call our centralized ambulance service or find the nearest emergency hospital.',
    'emergency.call907': 'Call 907',
    'emergency.findER': 'Find Nearest ER',
    'emergency.ambulanceService': 'Ambulance Services',
    'emergency.ambulanceDesc': 'Centralized dispatch for all major ambulance providers in Addis Ababa.',
    'emergency.hospitalsTitle': 'Emergency Hospitals',
    'emergency.hospitalsDesc': 'Real-time availability of ER beds and specialized trauma centers.',
    'emergency.firstAidTitle': 'First Aid Support',
    'emergency.firstAidDesc': 'Instant tele-consultation for first aid guidance while help is on the way.',
    'emergency.ambulanceNumbers': 'Ambulance Numbers',
    'emergency.whatToDo': 'What to do during emergencies',
    'emergency.do': 'What to Do',
    'emergency.dont': 'What NOT to Do',
    'emergency.heartAttack.title': 'Heart Attack',
    'emergency.heartAttack.do': 'Call 907 immediately. Help the person sit down and stay calm. Loosen tight clothing.',
    'emergency.heartAttack.dont': 'Do not leave the person alone. Do not wait to see if symptoms go away.',
    'emergency.stroke.title': 'Stroke',
    'emergency.stroke.do': 'Use FAST (Face, Arms, Speech, Time). Call 907 immediately. Note the time symptoms started.',
    'emergency.stroke.dont': 'Do not give them food or drink. Do not let them "sleep it off".',
    'emergency.choking.title': 'Choking',
    'emergency.choking.do': 'Encourage coughing. Give 5 back blows followed by 5 abdominal thrusts.',
    'emergency.choking.dont': 'Do not try to reach for the object if you cannot see it clearly.',
    'emergency.bleeding.title': 'Severe Bleeding',
    'emergency.bleeding.do': 'Apply direct pressure with a clean cloth. Elevate the wound above heart level.',
    'emergency.bleeding.dont': 'Do not remove the cloth if it gets soaked; add more on top. Do not use a tourniquet unless trained.',
    'emergency.burns.title': 'Burns',
    'emergency.burns.do': 'Run cool (not cold) water over the burn for 10-20 minutes. Cover with sterile dressing.',
    'emergency.burns.dont': 'Do not use ice, butter, or ointments. Do not pop blisters.',
    'emergency.seizures.title': 'Seizures',
    'emergency.seizures.do': 'Clear the area of sharp objects. Put something soft under their head. Time the seizure.',
    'emergency.seizures.dont': 'Do not restrain the person. Do not put anything in their mouth.',
    'emergency.redCross': 'Red Cross',
    'emergency.tebita': 'Tebita',
    'emergency.addisCardiac': 'Addis Cardiac',
    'emergency.police': 'Police',
    'login.title': 'Welcome Back',
    'login.subtitle': 'Sign in to access your health dashboard',
    'login.googleSignIn': 'Sign in with Google',
    'login.terms': 'By signing in, you agree to our Terms of Service and Privacy Policy.',
    'login.error': 'Authentication failed. Please try again.',
    'login.email': 'Email Address',
    'login.password': 'Password',
    'login.signIn': 'Sign In',
    'login.signUp': 'Sign Up',
    'login.orContinueWith': 'Or continue with',
    'login.googleAccount': 'Google Account',
    'login.dontHaveAccount': "Don't have an account?",
    'login.alreadyHaveAccount': 'Already have an account?',
    'login.welcomeBack': 'Welcome back!',
    'login.createAccount': 'Create your account',
    'footer.description': 'Revolutionizing healthcare access in Ethiopia through technology. Connecting patients with the best medical professionals and facilities.',
    'footer.quickLinks': 'Quick Links',
    'footer.findDoctor': 'Find a Doctor',
    'footer.hospitalsList': 'Hospitals List',
    'footer.labServices': 'Lab Services',
    'footer.emergencyHelp': 'Emergency Help',
    'footer.forProviders': 'For Providers',
    'footer.joinDoctor': 'Join as a Doctor',
    'footer.registerHospital': 'Register Hospital',
    'footer.partnerClinics': 'Partner Clinics',
    'footer.healthcareApis': 'Healthcare APIs',
    'footer.contactUs': 'Contact Us',
    'footer.rights': 'All rights reserved.',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.termsOfService': 'Terms of Service',
    'footer.cookiePolicy': 'Cookie Policy',
    'booking.consultNow': 'Consult Now',
    'booking.bookAppointment': 'Book Appointment',
    'booking.requestReceived': 'Request Received!',
    'booking.bookingConfirmed': 'Booking Confirmed!',
    'booking.reachOutSoon': 'we will reach you out soon',
    'booking.yourBookingConfirmed': 'your booking confirmed',
    'booking.close': 'Close',
    'booking.fullName': 'Full Name',
    'booking.fullNamePlaceholder': 'Enter your full name',
    'booking.age': 'Age (Y / M / D)',
    'booking.specialtyNeeded': 'Specialty Needed',
    'booking.specialtyPlaceholder': 'e.g. Cardiology',
    'booking.hospital': 'Hospital',
    'booking.hospitalPlaceholder': 'Enter hospital name',
    'booking.preferredDate': 'Preferred Date',
    'booking.preferredTime': 'Preferred Time',
    'booking.specificDoctor': 'Specific Doctor (Optional)',
    'booking.doctorPlaceholder': "Enter doctor's name if you have a preference",
    'booking.message': 'Message (Optional)',
    'booking.messagePlaceholder': 'Any additional information or symptoms?',
    'booking.processing': 'Processing...',
    'booking.requestConsultation': 'Request Consultation',
    'booking.confirmBooking': 'Confirm Booking',
    'partners.title': 'Partners & Integrations',
    'partners.subtitle': 'Join our network of healthcare professionals and institutions to revolutionize healthcare in Ethiopia.',
    'partners.joinDoctor': 'Join as a Doctor',
    'partners.registerHospital': 'Register Hospitals',
    'partners.partnerClinics': 'Partner Clinics',
    'partners.healthcareApis': 'Healthcare APIs',
    'partners.doctorTooltip': 'Connect with patients and manage your practice digitally.',
    'partners.hospitalTooltip': 'Increase patient reach, access digital appointment system, integrate with MedLink dashboard.',
    'partners.clinicTooltip': 'Grow your patient base, integrate with MedLink Ethiopia, manage appointments online.',
    'partners.apiTooltip': 'Integrate MedLink services into your own healthcare applications.',
    'form.fullName': 'Full Name',
    'form.specialty': 'Specialty',
    'form.hospitalAffiliation': 'Hospital Affiliation',
    'form.licenseNumber': 'License Number',
    'form.email': 'Email',
    'form.phone': 'Phone',
    'form.hospitalName': 'Hospital Name',
    'form.location': 'Location',
    'form.contactPerson': 'Contact Person',
    'form.servicesOffered': 'Services Offered',
    'form.logoUpload': 'Logo Upload (Optional)',
    'form.clinicName': 'Clinic Name',
    'form.city': 'City',
    'form.certifications': 'Certifications (Optional)',
    'form.submit': 'Submit Application',
    'form.requestApi': 'Request API Access',
    'form.successDoctor': 'Thank you! Our team will review your application within 24–48 hours.',
    'form.successHospital': 'Thank you! Your hospital will be verified and added to MedLink Ethiopia.',
    'form.successClinic': 'Thank you! Your clinic will be verified and added to MedLink Ethiopia.',
    'form.successApi': 'Your request has been received. Our team will contact you with integration details.',
    'form.apiEndpoints': 'API Endpoints',
    'form.authInfo': 'Authentication Info',
    'form.exampleRequest': 'Example Request',
    'form.exampleResponse': 'Example Response',
    'hero.title': 'Premium Healthcare for a Healthier Ethiopia',
    'hero.subtitle': 'Experience world-class medical services with MedLink Ethiopia. We connect you with the finest specialists and state-of-the-art facilities across the nation.',
    'stats.years': 'Years Experience',
    'stats.specialists': 'Specialists',
    'stats.emergency': 'Emergency',
    'common.trustedHealthcare': 'Trusted Healthcare Partner',
    'exploreServices': 'Explore Services',
    manageAppointments: 'Manage your medical visits',
    days_short: 'd',
    hours_short: 'h',
    minutes_short: 'm',
    seconds_short: 's',
  },
  am: {
    'auth.login': 'ግባ',
    'auth.signup': 'ተመዝገብ',
    'auth.logout': 'ውጣ',
    welcomeToMedLink: 'ወደ ሜድሊንክ ኢትዮጵያ እንኳን ደህና መጡ',
    welcomeBack: 'እንኳን ደህና መጡ',
    guestWelcome: 'ወደ ሜድሊንክ ኢትዮጵያ እንኳን ደህና መጡ',
    guestSubtitle: 'ቀጠሮዎችዎን እና የጤና መዝገቦችዎን ለማስተዳደር እኛን ይቀላቀሉ።',
    loginToView: 'የእርስዎን መረጃ ለማየት ይግቡ',
    ourServices: 'የእኛ የጤና አገልግሎቶች',
    servicesSubtitle: 'ሜድሊንክ የሕክምና ጉዞዎን እንከን የለሽ እና ቀልጣፋ ለማድረግ አጠቃላይ የዲጂታል የጤና እንክብካቤ መሳሪያዎችን ያቀርባል።',
    findDoctorDesc: 'በኢትዮጵያ ውስጥ ያሉ ከፍተኛ ስፔሻሊስቶችን በልዩ ሙያ፣ በሆስፒታል ወይም በደረጃ ይፈልጉ።',
    bookAppointmentDesc: 'ከዋና ዋና ሆስፒታሎች ቅጽበታዊ ተገኝነት ጋር ጉብኝቶችዎን ወዲያውኑ ያቅዱ።',
    emergencyDesc: 'በአቅራቢያዎ የሚገኘውን የአደጋ ጊዜ ክፍል ያግኙ እና እያንዳንዱ ሰከንድ በሚቆጠርበት ጊዜ አፋጣኝ እርዳታ ያግኙ።',
    labResultsDesc: 'የምርመራ ሪፖርቶችዎን ከየትኛውም ቦታ፣ በማንኛውም ጊዜ ደህንነቱ በተጠበቀ ሁኔታ ያግኙ እና ይከታተሉ።',
    featuredHospitals: 'ተለይተው የቀረቡ ሆስፒታሎች',
    hospitalsSubtitle: 'በአገሪቱ ውስጥ ካሉ በጣም ታዋቂ የሕክምና ተቋማት ጋር በመተባበር።',
    viewAllHospitals: 'ሁሉንም ሆስፒታሎች ይመልከቱ',
    howMedLinkWorks: 'ሜድሊንክ እንዴት እንደሚሰራ',
    step1Title: 'መገለጫዎን ይፍጠሩ',
    step1Desc: 'ይመዝገቡ እና የሕክምና ታሪክዎን እና ምርጫዎችዎን ደህንነቱ በተጠበቀ ሁኔታ ያስቀምጡ።',
    step2Title: 'ይፈልጉ እና ያስይዙ',
    step2Desc: 'ስፔሻሊስቶችን ይፈልጉ እና በሚመችዎ ጊዜ ቀጠሮ ይያዙ።',
    step3Title: 'እንክብካቤ ያግኙ',
    step3Desc: 'ሆስፒታሉን ይጎብኙ እና ዓለም አቀፍ ደረጃውን የጠበቀ የሕክምና ክትትል ያግኙ።',
    step4Title: 'ውጤቶችን ይከታተሉ',
    step4Desc: 'የመድኃኒት ትዕዛዞችዎን እና የላብራቶሪ ውጤቶችዎን በቀጥታ በዳሽቦርድዎ ላይ ያግኙ።',
    healthTipTitle: 'የየቀኑ የጤና ምክር',
    healthTipBody: 'ውሃ ይጠጡ! በቀን ቢያንስ 8 ብርጭቆ ውሃ መጠጣት የኃይል መጠንዎን ለመጠበቅ እና አጠቃላይ የአካል ክፍሎችን ስራ ይረዳል።',
    'tips.1.title': 'ውሃ መጠጣት',
    'tips.1.body': 'ሰውነትዎ በጥሩ ሁኔታ እንዲሠራ በቀን ቢያንስ 8 ብርጭቆ ውሃ ይጠጡ።',
    'tips.2.title': 'ጥሩ እንቅልፍ',
    'tips.2.body': 'ሰውነትዎ እንዲያገግም እና ኃይል እንዲያገኝ በየምሽቱ ከ7-9 ሰአታት ጥራት ያለው እንቅልፍ ለማግኘት ይሞክሩ።',
    'tips.3.title': 'መደበኛ የአካል ብቃት እንቅስቃሴ',
    'tips.3.body': 'እንደ ፈጣን እርምጃ ያሉ ለ30 ደቂቃዎች የሚደረጉ መጠነኛ እንቅስቃሴዎች የልብ ጤናን በእጅጉ ያሻሽላሉ።',
    'tips.4.title': 'የተመጣጠነ ምግብ',
    'tips.4.body': 'ለተለያዩ አስፈላጊ ቪታሚኖች በምግብዎ ውስጥ ተጨማሪ ባለቀለም አትክልቶችን ያካትቱ።',
    'tips.5.title': 'የአእምሮ ጤና',
    'tips.5.body': 'ውጥረትን ለመቀነስ እና ትኩረትን ለማሻሻል በቀን ለ10 ደቂቃ ማሰላሰልን ይለማመዱ።',
    'tips.6.title': 'የአቀማመጥ ሁኔታ',
    'tips.6.body': 'ከኮምፒውተር ወይም ስልክ ስክሪን አዘውትረው እረፍት ይውሰዱ እና የአንገት እና የጀርባ ህመምን ለመከላከል ሰውነትዎን ያፍታቱ።',
    'tips.7.title': 'የእጅ ንፅህና',
    'tips.7.body': 'በተለይ ከምግብ በፊት ጀርሞችን ለመከላከል እጅዎን በተደጋጋሚ ይታጠቡ።',
    today: 'ዛሬ',
    learnMore: 'ተጨማሪ ይወቁ',
    loginToAccessRecords: 'የሕክምና መዝገቦችዎን እና ቀጠሮዎችዎን ለማግኘት ይግቡ።',
    bookAppointmentNow: 'አሁኑኑ ቀጠሮ ይያዙ',
    bookingDescription: 'በኢትዮጵያ ውስጥ ካሉ ምርጥ ዶክተሮች እና ሆስፒታሎች ጋር ይገናኙ። ጉብኝትዎን ለማቀድ እና የጤና ጉዞዎን ለማስተዳደር ይግቡ።',
    emergencyCare: 'የአደጋ ጊዜ እንክብካቤ',
    needEmergencyCare: 'አፋጣኝ የሕክምና እርዳታ ይፈልጋሉ?',
    emergencySubtitle: 'ለአስቸኳይ የህክምና ፍላጎቶች 24/7 ይገኛል።',
    'emergency.available247': '24/7 ይገኛል',
    dashboard: 'ዳሽቦርድ',
    hello: 'ሰላም',
    welcome: 'ወደ ጤና ዳሽቦርድዎ እንኳን ደህና መጡ። ዛሬ ምን እየተከናወነ እንደሆነ እነሆ።',
    upcoming: 'የሚመጡ',
    prescriptions: 'የመድኃኒት ትዕዛዞች',
    labResults: 'የላብራቶሪ ውጤቶች',
    notifications: 'ማሳወቂያዎች',
    upcomingAppointments: 'የሚመጡ ቀጠሮዎች',
    recentLabResults: 'የቅርብ ጊዜ የላብራቶሪ ውጤቶች',
    viewAll: 'ሁሉንም ይመልከቱ',
    noAppointments: 'ምንም የሚመጡ ቀጠሮዎች አልተገኙም።',
    noLabResults: 'እስካሁን ምንም የላብ ውጤቶች የሉም።',
    noPrescriptions: 'ምንም ንቁ የመድኃኒት ትዕዛዞች የሉም።',
    bookFirstVisit: 'የመጀመሪያ ጉብኝትዎን ያስይዙ',
    activePrescriptions: 'ንቁ የመድኃኒት ትዕዛዞች',
    quickActions: 'ፈጣን እርምጃዎች',
    findDoctor: 'ዶክተር ያግኙ',
    emergency: 'አደጋ ጊዜ',
    hospitals: 'ሆስፒታሎች',
    profile: 'መገለጫ',
    appointmentDetails: 'የቀጠሮ ዝርዝሮች',
    cancelAppointment: 'ቀጠሮ ሰርዝ',
    confirmCancel: 'እርግጠኛ ነዎት ይህንን ቀጠሮ መሰረዝ ይፈልጋሉ?',
    yes: 'አዎ',
    no: 'አይ',
    close: 'ዝጋ',
    patient: 'ታካሚ',
    age: 'እድሜ',
    doctor: 'ዶክተር',
    specialty: 'ልዩ ሙያ',
    hospital: 'ሆስፒታል',
    dateTime: 'ቀን እና ሰዓት',
    message: 'መልዕክት',
    notes: 'ማስታወሻዎች',
    medication: 'መድኃኒት',
    dosage: 'መጠን',
    instructions: 'መመሪያዎች',
    prescribedOn: 'የታዘዘው በ',
    testName: 'የምርመራ ስም',
    result: 'ውጤት',
    status: 'ሁኔታ',
    performedAt: 'የተከናወነው በ',
    on: 'በ',
    notificationPermission: 'የየቀኑ የጤና ማሳወቂያዎችን መቀበል ይፈልጋሉ?',
    allow: 'ፍቀድ',
    deny: 'አትፍቀድ',
    notificationTitle: 'የየቀኑ የጤና ማሳሰቢያ',
    notificationBody: 'የዛሬውን የሚመጡ ቀጠሮዎችዎን እና የመድኃኒት ትዕዛዞችዎን ያረጋግጡ።',
    'nav.home': 'ቤት',
    'nav.hospitals': 'ሆስፒታሎች',
    'nav.doctors': 'ዶክተሮች',
    'nav.labs': 'ላብራቶሪ እና ምርመራ',
    'nav.pharmacy': 'ፋርማሲ',
    'nav.emergency': 'አደጋ',
    'nav.profile': 'መገለጫ',
    'nav.dashboard': 'ዳሽቦርድ',
    'common.search': 'ፈልግ',
    'common.viewProfile': 'መገለጫ ይመልከቱ',
    'common.consultNow': 'አሁን ያማክሩ',
    'common.bookAppointment': 'ቀጠሮ ይያዙ',
    'common.specialties': 'ልዩ ሙያዎች',
    'common.topDoctors': 'ምርጥ ዶክተሮች',
    'common.allSpecialties': 'ሁሉም ልዩ ሙያዎች',
    'common.searchPlaceholder': 'ዶክተሮችን በስም፣ በሆስፒታል ወይም በሙያ ይፈልጉ...',
    'common.clearFilters': 'ማጣሪያዎችን እና ፍለጋን አጽዳ',
    'common.noDoctorsFound': 'ከፍለጋዎ ጋር የሚዛመዱ ዶክተሮች አልተገኙም።',
    'common.professionalSummary': 'የሙያ ማጠቃለያ',
    'common.affiliatedHospitals': 'ተያያዥ ሆስፒታሎች',
    'common.availableTimes': 'የሚገኙ ሰዓታት',
    'common.bookConsultation': 'ምክክር ይያዙ',
    'common.rating': 'ደረጃ',
    'common.experience': 'ልምድ',
    'common.years': 'ዓመታት',
    'common.specialists': 'ስፔሻሊስቶች',
    'common.comprehensiveCare': 'ሁሉን አቀፍ የሕክምና እንክብካቤ',
    'common.connectWithSpecialists': 'ለባለሙያ ምክክር እና ሕክምና በተለያዩ የሕክምና ዘርፎች ካሉ ስፔሻሊስቶች ጋር ይገናኙ።',
    'common.searchResults': 'የፍለጋ ውጤቶች',
    'common.found': 'ተገኝቷል',
    'common.doctorsMatching': 'የሚዛመዱ ዶክተሮች',
    'common.viewAll': 'ሁሉንም ይመልከቱ',
    'common.doctors': 'ዶክተሮች',
    'common.noDoctorsSpecialty': 'ለዚህ ልዩ ሙያ በአሁኑ ጊዜ ምንም ዶክተሮች አልተገኙም።',
    'common.more': 'ተጨማሪ',
    'common.facility': 'ተቋም',
    'common.verified': 'የተረጋገጠ',
    'common.open': 'ክፍት',
    'common.open247': '24/7 ክፍት',
    'common.generalSpecialist': 'አጠቃላይ ስፔሻሊስት',
    'common.booking': 'ቦታ ማስያዝ',
    'hero.headline': 'ኢትዮጵያን ከዘመናዊ የጤና አገልግሎት ጋር ማገናኘት',
    'hero.subheadline': 'የላቀ ምርመራ • የታመኑ ስፔሻሊስቶች • አዛኝ የታካሚ እንክብካቤ',
    'dashboard.portal': 'ዳሽቦርድ / የታካሚ ፖርታል',
    'dashboard.guestPrompt': 'ወደ ሜድሊንክ ኢትዮጵያ ዳሽቦርድ እንኳን ደህና መጡ - ቀጠሮዎችዎን፣ የምርመራ ውጤቶችዎን እና የእንክብካቤ እቅዶችዎን ያግኙ። እባክዎ ለመቀጠል ይግቡ።',
    'leadingMedicalService': 'በኢትዮጵያ ቀዳሚው የኦንላይን የህክምና አገልግሎት',
    'whyChooseUs': 'ለምን ሜድሊንክን ይመርጣሉ?',
    'whyChooseUsSubtitle': 'በፈጠራ እና በርህራሄ ከፍተኛ ጥራት ያለው የጤና አገልግሎት ለመስጠት ቁርጠኞች ነን።',
    'reason1Title': 'ባለሙያ ስፔሻሊስቶች',
    'reason1Desc': 'በሁሉም የሕክምና ዘርፎች ከፍተኛ ብቃት ያላቸው እና ልምድ ያላቸው የሕክምና ባለሙያዎችን ያግኙ።',
    'reason2Title': 'ቀላል ቀጠሮ ማስያዝ',
    'reason2Desc': 'ጊዜዎን እና ጥረትዎን በመቆጠብ ቀጠሮዎችን ወዲያውኑ ይያዙ።',
    'reason3Title': 'ደህንነቱ የተጠበቀ መዝገቦች',
    'reason3Desc': 'የሕክምና ታሪክዎ እና የምርመራ ውጤቶችዎ ደህንነቱ በተጠበቀ ሁኔታ ይቀመጣሉ እና በእርስዎ ብቻ ይገኛሉ።',
    'ourMission': 'የእኛ ተልዕኮ',
    'ourMissionDesc': 'በዘመናዊ ዲጂታል መፍትሄዎች በታካሚዎች እና በአገልግሎት ሰጪዎች መካከል ያለውን ልዩነት በማጥበብ በኢትዮጵያ የጤና አገልግሎት ተደራሽነትን ማሻሻል።',
    'newsUpdates': 'ዜና እና ወቅታዊ መረጃዎች',
    'newsUpdatesSubtitle': 'ስለ የቅርብ ጊዜ የጤና እድገቶች እና የሜድሊንክ ባህሪያት መረጃ ያግኙ።',
    'news1Title': 'ሜድሊንክ ወደ ክልል ከተሞች ተስፋፋ',
    'news1Date': 'መጋቢት 11 ቀን 2018 ዓ.ም',
    'news1Desc': 'ዘመናዊ የጤና አገልግሎትን ወደ እርስዎ ለማቅረብ ወደ ባህር ዳር እና ሀዋሳ መስፋፋታችንን ስናበስር በደስታ ነው።',
    'news2Title': 'አዲስ የቴሌሜዲሲን አገልግሎት ተጀመረ',
    'news2Date': 'መጋቢት 6 ቀን 2018 ዓ.ም',
    'news2Desc': 'በአዲሱ የቪዲዮ ምክክር መሳሪያችን አማካኝነት ከቤትዎ ሆነው ዶክተርዎን ያማክሩ።',
    'hospitals.title': 'ከፍተኛ ደረጃ የተሰጣቸው ሆስፒታሎች',
    'hospitals.subtitle': 'በአቅራቢያዎ ያሉ ምርጥ የሕክምና ተቋማትን በባለሙያ እንክብካቤ እና በዘመናዊ ቴክኖሎጂ ያግኙ።',
    'hospitals.searchPlaceholder': 'ሆስፒታሎችን በስም፣ በቦታ ወይም በልዩ ሙያ ይፈልጉ...',
    'hospitals.allCategories': 'ሁሉም ምድቦች',
    'hospitals.public': 'የመንግስት',
    'hospitals.private': 'የግል',
    'hospitals.general': 'አጠቃላይ',
    'hospitals.specialized': 'ልዩ',
    'hospitals.maternity': 'ወሊድ',
    'hospitals.children': 'ልጆች',
    'hospitals.emergency': 'አደጋ',
    'hospitals.noHospitals': 'ከእርስዎ መስፈርት ጋር የሚዛመዱ ሆስፒታሎች አልተገኙም።',
    'hospitals.viewDetails': 'ዝርዝሮችን ይመልከቱ',
    'hospitals.bookVisit': 'ጉብኝት ይያዙ',
    'hospitals.about': 'ስለ',
    'hospitals.services': 'አገልግሎቶች',
    'hospitals.location': 'ቦታ',
    'hospitals.contact': 'እውቂያ',
    'hospitals.website': 'ድረ-ገጽ',
    'hospitals.openNow': 'አሁን ክፍት ነው',
    'hospitals.closed': 'ተዘግቷል',
    'hospitals.beds': 'አልጋዎች',
    'hospitals.staff': 'ሰራተኞች',
    'hospitals.emergency247': '24/7 የአደጋ ጊዜ',
    'hospitals.icu': 'ICU ይገኛል',
    'hospitals.pharmacy': 'ፋርማሲ',
    'hospitals.lab': 'ላብራቶሪ',
    'hospitals.radiology': 'ራዲዮሎጂ',
    'hospitals.ambulance': 'አምቡላንስ',
    'hospitals.insurance': 'ኢንሹራንስ ተቀባይነት አለው',
    'hospitals.parking': 'ፓርኪንግ ይገኛል',
    'hospitals.wifi': 'ነፃ ዋይፋይ',
    'hospitals.cafeteria': 'ካፌቴሪያ',
    'hospitals.bloodBank': 'የደም ባንክ',
    'hospitals.dialysis': 'የዲያሊሲስ ማእከል',
    'profile.title': 'የእርስዎ ፕሮፋይል',
    'profile.subtitle': 'የመለያ ቅንብሮችዎን እና የግል መረጃዎን ያስተዳድሩ።',
    'profile.displayName': 'የመገለጫ ስም',
    'profile.email': 'የኢሜል አድራሻ',
    'profile.emailNote': 'ኢሜል መቀየር አይቻልም።',
    'profile.saveChanges': 'ለውጦችን አስቀምጥ',
    'profile.accountDetails': 'የመለያ ዝርዝሮች',
    'profile.memberSince': 'አባል የሆኑት ከ',
    'profile.accountStatus': 'የመለያ ሁኔታ',
    'profile.verified': 'የተረጋገጠ',
    'profile.signOut': 'ከመለያ ውጣ',
    'profile.updateSuccess': 'ፕሮፋይል በተሳካ ሁኔታ ተዘምኗል!',
    'profile.updateError': 'ፕሮፋይል ሲዘምን ስህተት ተከስቷል',
    'profile.placeholderName': 'ሙሉ ስምዎን ያስገቡ',
    'labs.title': 'የላቦራቶሪ አገልግሎቶች',
    'labs.subtitle': 'የምርመራ ውጤቶችዎን ያግኙ እና በአቅራቢያዎ ያሉ የምርመራ ማዕከላትን ይፈልጉ።',
    'labs.searchPlaceholder': 'ምርመራዎችን ወይም ማዕከላትን ይፈልጉ...',
    'labs.recentResults': 'የቅርብ ጊዜ ውጤቶች',
    'labs.findCenter': 'የላብ ማእከል ፈልግ',
    'labs.bookTest': 'ምርመራ ይያዙ',
    'labs.noResults': 'እስካሁን ምንም የላብ ውጤቶች የሉም።',
    'labs.viewReport': 'ሪፖርቱን እይ',
    'labs.testName': 'የምርመራ ስም',
    'labs.center': 'ማዕከል',
    'labs.result': 'ውጤት',
    'labs.status': 'ሁኔታ',
    'labs.date': 'ቀን',
    'labs.imaging': 'ኢሜጂንግ',
    'labs.laboratory': 'ላቦራቶሪ',
    'labs.radiology': 'ራዲዮሎጂ',
    'labs.general': 'አጠቃላይ',
    'labs.pharmacy': 'ፋርማሲ',
    'emergency.title': 'የአደጋ ጊዜ አገልግሎቶች',
    'emergency.subtitle': 'አፋጣኝ እርዳታ እና ወሳኝ የእንክብካቤ መረጃ።',
    'emergency.callNow': 'አሁን ለአደጋ ጊዜ ይደውሉ',
    'emergency.nearbyER': 'በአቅራቢያ ያሉ የአደጋ ጊዜ ክፍሎች',
    'emergency.firstAid': 'የመጀመሪያ እርዳታ መመሪያ',
    'emergency.ambulance': 'አምቡላንስ ይጠይቁ',
    'emergency.location': 'የእርስዎ አካባቢ',
    'emergency.sharingLocation': 'ለፈጣን ምላሽ አካባቢዎን በማጋራት ላይ...',
    'labs.medStoreTitle': 'መድኃኒቶችን በመስመር ላይ ይዘዙ',
    'labs.medStoreSubtitle': 'በአቅራቢያዎ ያሉ ፋርማሲዎችን ያግኙ፣ የመድኃኒት መኖርን ያረጋግጡ እና በቤትዎ ድረስ እንዲመጣልዎ ያድርጉ።',
    'labs.medStoreFeature1': 'በትዕዛዝ ወረቀት ይፈልጉ',
    'labs.medStoreFeature2': 'የመድኃኒት መኖርን ያረጋግጡ',
    'labs.medStoreFeature3': 'በአዲስ አበባ ውስጥ የቤት ለቤት አቅርቦት',
    'labs.medStoreFeature4': 'የተረጋገጡ ፋርማሲዎች ብቻ',
    'labs.openMedStore': 'MedStoreን ይክፈቱ',
    'emergency.response': 'የአደጋ ጊዜ ምላሽ',
    'emergency.urgentTitle': 'አፋጣኝ የሕክምና እርዳታ ይፈልጋሉ?',
    'emergency.urgentSubtitle': 'የእኛ የ24/7 የአደጋ ጊዜ ጥሪ ማእከል ለመርዳት ዝግጁ ነው። የእኛን ማዕከላዊ የአምቡላንስ አገልግሎት ይደውሉ ወይም በአቅራቢያዎ የሚገኘውን የአደጋ ጊዜ ሆስፒታል ያግኙ።',
    'emergency.call907': 'ወደ 907 ይደውሉ',
    'emergency.findER': 'በአቅራቢያ ያለ ER ያግኙ',
    'emergency.ambulanceService': 'የአምቡላንስ አገልግሎቶች',
    'emergency.ambulanceDesc': 'በአዲስ አበባ ውስጥ ላሉ ዋና ዋና የአምቡላንስ አቅራቢዎች ማዕከላዊ ጥሪ ማእከል።',
    'emergency.hospitalsTitle': 'የአደጋ ጊዜ ሆስፒታሎች',
    'emergency.hospitalsDesc': 'የER አልጋዎች እና ልዩ የድንገተኛ አደጋ ማዕከላት መኖርን በቅጽበት ማወቅ።',
    'emergency.firstAidTitle': 'የመጀመሪያ እርዳታ ድጋፍ',
    'emergency.firstAidDesc': 'እርዳታ እስኪመጣ ድረስ ፈጣን የስልክ ምክክር ለመጀመሪያ እርዳታ መመሪያ።',
    'emergency.ambulanceNumbers': 'የአምቡላንስ ስልኮች',
    'emergency.whatToDo': 'በአደጋ ጊዜ ምን ማድረግ እንዳለብዎ',
    'emergency.do': 'ምን ማድረግ አለብዎት',
    'emergency.dont': 'ምን ማድረግ የለብዎትም',
    'emergency.heartAttack.title': 'የልብ ድካም',
    'emergency.heartAttack.do': 'ወዲያውኑ ወደ 907 ይደውሉ። ግለሰቡ እንዲቀመጥ እና እንዲረጋጋ ይርዱት። ጥብቅ ልብሶችን ያላላሉ።',
    'emergency.heartAttack.dont': 'ግለሰቡን ብቻውን አይተዉት። ምልክቶቹ ይጠፉ እንደሆነ ለማየት አይጠብቁ።',
    'emergency.stroke.title': 'ስትሮክ (ድንገተኛ የጭንቅላት ደም መፍሰስ)',
    'emergency.stroke.do': 'FAST (ፊት፣ እጅ፣ ንግግር፣ ጊዜ) ይጠቀሙ። ወዲያውኑ ወደ 907 ይደውሉ። ምልክቶቹ የጀመሩበትን ሰዓት ይያዙ።',
    'emergency.stroke.dont': 'ምግብ ወይም መጠጥ አይስጡ። እንዲተኙ አይፍቀዱላቸው።',
    'emergency.choking.title': 'መታነቅ (ትምታ)',
    'emergency.choking.do': 'እንዲያስሉ ያበረታቷቸው። 5 ጊዜ ጀርባቸውን ይምቱ፣ ከዚያም 5 ጊዜ ሆዳቸውን ይጫኑ።',
    'emergency.choking.dont': 'እቃውን በግልጽ ካላዩት በእጅዎ ለማውጣት አይሞክሩ።',
    'emergency.bleeding.title': 'ከፍተኛ የደም መፍሰስ',
    'emergency.bleeding.do': 'በንጹህ ጨርቅ በቀጥታ ይጫኑ። የቆሰለውን አካል ከልብ በላይ ከፍ ያድርጉት።',
    'emergency.bleeding.dont': 'ጨርቁ በደም ቢርስ አይቀይሩት፤ ሌላ በላዩ ላይ ይጨምሩ። ካልሰለጠኑ በስተቀር ደም መዝጊያ (tourniquet) አይጠቀሙ።',
    'emergency.burns.title': 'ቃጠሎ',
    'emergency.burns.do': 'ለ10-20 ደቂቃ በቀዝቃዛ (በረዶ ያልሆነ) ውሃ ያጥቡት። በንጹህ ጨርቅ ይሸፍኑ።',
    'emergency.burns.dont': 'በረዶ፣ ቅቤ ወይም ቅባት አይጠቀሙ። የተነፋውን ቆዳ አይውጉት።',
    'emergency.seizures.title': 'የሚጥል በሽታ (መንቀጥቀጥ)',
    'emergency.seizures.do': 'አካባቢውን ከሹል ነገሮች ያጽዱ። ከራሳቸው ስር ለስላሳ ነገር ያድርጉ። ሰዓት ይያዙ።',
    'emergency.seizures.dont': 'ሰውየውን አይያዙት። በአፋቸው ውስጥ ምንም ነገር አያድርጉ።',
    'emergency.redCross': 'ቀይ መስቀል',
    'emergency.tebita': 'ተቢታ',
    'emergency.addisCardiac': 'አዲስ ካርዲያክ',
    'emergency.police': 'ፖሊስ',
    'login.title': 'እንኳን ደህና መጡ',
    'login.subtitle': 'የጤና ዳሽቦርድዎን ለማግኘት ይግቡ',
    'login.googleSignIn': 'በGoogle ይግቡ',
    'login.terms': 'በመግባትዎ በአገልግሎት ውላችን እና በግላዊነት ፖሊሲያችን ተስማምተዋል።',
    'login.error': 'መግባት አልተቻለም። እባክዎ እንደገና ይሞክሩ።',
    'login.email': 'የኢሜል አድራሻ',
    'login.password': 'የይለፍ ቃል',
    'login.signIn': 'ግባ',
    'login.signUp': 'ተመዝገብ',
    'login.orContinueWith': 'ወይም በዚህ ይቀጥሉ',
    'login.googleAccount': 'የGoogle መለያ',
    'login.dontHaveAccount': 'መለያ የለዎትም?',
    'login.alreadyHaveAccount': 'ቀድሞውኑ መለያ አለዎት?',
    'login.welcomeBack': 'እንኳን ደህና መጡ!',
    'login.createAccount': 'መለያዎን ይፍጠሩ',
    'footer.description': 'በቴክኖሎጂ አማካኝነት በኢትዮጵያ የጤና አገልግሎት ተደራሽነትን ማሻሻል። ታካሚዎችን ከምርጥ የህክምና ባለሙያዎች እና ተቋማት ጋር ማገናኘት።',
    'footer.quickLinks': 'ፈጣን ሊንኮች',
    'footer.findDoctor': 'ዶክተር ፈልግ',
    'footer.hospitalsList': 'የሆስፒታሎች ዝርዝር',
    'footer.labServices': 'የላቦራቶሪ አገልግሎቶች',
    'footer.emergencyHelp': 'የአደጋ ጊዜ እርዳታ',
    'footer.forProviders': 'ለአገልግሎት ሰጪዎች',
    'footer.joinDoctor': 'እንደ ዶክተር ይቀላቀሉ',
    'footer.registerHospital': 'ሆስፒታል ያስመዝግቡ',
    'footer.partnerClinics': 'አጋር ክሊኒኮች',
    'footer.healthcareApis': 'የጤና እንክብካቤ ኤፒአይዎች',
    'footer.contactUs': 'ያግኙን',
    'footer.rights': 'መብቱ በህግ የተጠበቀ ነው።',
    'footer.privacyPolicy': 'የግላዊነት ፖሊሲ',
    'footer.termsOfService': 'የአገልግሎት ውል',
    'footer.cookiePolicy': 'የኩኪ ፖሊሲ',
    'booking.consultNow': 'አሁን ያማክሩ',
    'booking.bookAppointment': 'ቀጠሮ ይያዙ',
    'booking.requestReceived': 'ጥያቄው ደርሶናል!',
    'booking.bookingConfirmed': 'ቀጠሮው ተረጋግጧል!',
    'booking.reachOutSoon': 'በቅርቡ እናገኝዎታለን',
    'booking.yourBookingConfirmed': 'ቀጠሮዎ ተረጋግጧል',
    'booking.close': 'ዝጋ',
    'booking.fullName': 'ሙሉ ስም',
    'booking.fullNamePlaceholder': 'ሙሉ ስምዎን ያስገቡ',
    'booking.age': 'ዕድሜ (ዓመት / ወር / ቀን)',
    'booking.specialtyNeeded': 'የሚያስፈልገው ስፔሻሊቲ',
    'booking.specialtyPlaceholder': 'ምሳሌ፡ ካርዲዮሎጂ',
    'booking.hospital': 'ሆስፒታል',
    'booking.hospitalPlaceholder': 'የሆስፒታሉን ስም ያስገቡ',
    'booking.preferredDate': 'ተመራጭ ቀን',
    'booking.preferredTime': 'ተመራጭ ሰዓት',
    'booking.specificDoctor': 'የተወሰነ ዶክተር (አማራጭ)',
    'booking.doctorPlaceholder': 'ምርጫ ካለዎት የዶክተሩን ስም ያስገቡ',
    'booking.message': 'መልዕክት (አማራጭ)',
    'booking.messagePlaceholder': 'ማንኛውም ተጨማሪ መረጃ ወይም ምልክቶች?',
    'booking.processing': 'በሂደት ላይ...',
    'booking.requestConsultation': 'ምክክር ይጠይቁ',
    'booking.confirmBooking': 'ቀጠሮውን ያረጋግጡ',
    'partners.title': 'አጋሮች እና ውህደቶች',
    'partners.subtitle': 'በኢትዮጵያ የጤና አገልግሎትን ለማዘመን የጤና ባለሙያዎችን እና ተቋማትን መረባችንን ይቀላቀሉ።',
    'partners.joinDoctor': 'እንደ ዶክተር ይቀላቀሉ',
    'partners.registerHospital': 'ሆስፒታሎችን ያስመዝግቡ',
    'partners.partnerClinics': 'አጋር ክሊኒኮች',
    'partners.healthcareApis': 'የጤና እንክብካቤ ኤፒአይዎች',
    'partners.doctorTooltip': 'ከታካሚዎች ጋር ይገናኙ እና ስራዎን በዲጂታል መንገድ ያስተዳድሩ።',
    'partners.hospitalTooltip': 'የታካሚ ተደራሽነትን ይጨምሩ፣ የዲጂታል ቀጠሮ ስርዓትን ያግኙ፣ ከሜድሊንክ ዳሽቦርድ ጋር ይዋሃዱ።',
    'partners.clinicTooltip': 'የታካሚ መሰረትዎን ያሳድጉ፣ ከሜድሊንክ ኢትዮጵያ ጋር ይዋሃዱ፣ ቀጠሮዎችን በመስመር ላይ ያስተዳድሩ።',
    'partners.apiTooltip': 'የሜድሊንክ አገልግሎቶችን በራስዎ የጤና እንክብካቤ መተግበሪያዎች ውስጥ ያዋህዱ።',
    'form.fullName': 'ሙሉ ስም',
    'form.specialty': 'ልዩ ሙያ',
    'form.hospitalAffiliation': 'የሆስፒታል ግንኙነት',
    'form.licenseNumber': 'የፈቃድ ቁጥር',
    'form.email': 'ኢሜል',
    'form.phone': 'ስልክ',
    'form.hospitalName': 'የሆስፒታል ስም',
    'form.location': 'ቦታ',
    'form.contactPerson': 'ተጠሪ ሰው',
    'form.servicesOffered': 'የሚሰጡ አገልግሎቶች',
    'form.logoUpload': 'ሎጎ መጫኛ (አማራጭ)',
    'form.clinicName': 'የክሊኒክ ስም',
    'form.city': 'ከተማ',
    'form.certifications': 'የብቃት ማረጋገጫዎች (አማራጭ)',
    'form.submit': 'ማመልከቻውን ያስገቡ',
    'form.requestApi': 'የኤፒአይ መዳረሻ ይጠይቁ',
    'form.successDoctor': 'እናመሰግናለን! ቡድናችን ማመልከቻዎን በ24-48 ሰዓታት ውስጥ ይገመግመዋል።',
    'form.successHospital': 'እናመሰግናለን! ሆስፒታልዎ ተረጋግጦ ወደ ሜድሊንክ ኢትዮጵያ ይጨመራል።',
    'form.successClinic': 'እናመሰግናለን! ክሊኒክዎ ተረጋግጦ ወደ ሜድሊንክ ኢትዮጵያ ይጨመራል።',
    'form.successApi': 'ጥያቄዎ ደርሶናል። ቡድናችን የውህደት ዝርዝሮችን ይዞ ያገኝዎታል።',
    'form.apiEndpoints': 'የኤፒአይ መጨረሻ ነጥቦች',
    'form.authInfo': 'የማረጋገጫ መረጃ',
    'form.exampleRequest': 'የጥያቄ ምሳሌ',
    'form.exampleResponse': 'የምላሽ ምሳሌ',
    'hero.title': 'ለተሻለች ኢትዮጵያ ከፍተኛ ጥራት ያለው የጤና አገልግሎት',
    'hero.subtitle': 'ከሜድሊንክ ኢትዮጵያ ጋር ዓለም አቀፍ የሕክምና አገልግሎቶችን ያግኙ። በመላ አገሪቱ ካሉ ምርጥ ስፔሻሊስቶች እና ዘመናዊ ተቋማት ጋር እናገናኝዎታለን።',
    'stats.years': 'የልምድ ዓመታት',
    'stats.specialists': 'ስፔሻሊስቶች',
    'stats.emergency': 'አደጋ ጊዜ',
    'common.trustedHealthcare': 'የታመነ የጤና አጋር',
    'exploreServices': 'አገልግሎቶችን ያስሱ',
    manageAppointments: 'የሕክምና ጉብኝቶችዎን ያስተዳድሩ',
    days_short: 'ቀ',
    hours_short: 'ሰ',
    minutes_short: 'ደ',
    seconds_short: 'ሰከ',
  }
};

const AppContext = createContext<AppContextType | undefined>(undefined);

export const AppProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => (localStorage.getItem('lang') as Language) || 'en');
  const [theme, setTheme] = useState<Theme>(() => (localStorage.getItem('theme') as Theme) || 'light');
  const [partnerFormToOpen, setPartnerFormToOpen] = useState<'doctor' | 'hospital' | 'clinic' | 'api' | null>(null);
  const [cart, setCart] = useState<CartItem[]>(() => {
    const saved = localStorage.getItem('cart');
    return saved ? JSON.parse(saved) : [];
  });

  useEffect(() => {
    localStorage.setItem('cart', JSON.stringify(cart));
  }, [cart]);

  useEffect(() => {
    localStorage.setItem('lang', language);
  }, [language]);

  useEffect(() => {
    localStorage.setItem('theme', theme);
    console.log('Theme changed to:', theme);
    const root = window.document.documentElement;
    if (theme === 'dark') {
      root.classList.add('dark');
    } else {
      root.classList.remove('dark');
    }
  }, [theme]);

  const toggleTheme = () => setTheme(prev => prev === 'light' ? 'dark' : 'light');

  const t = (key: string, fallback?: string) => {
    return (translations[language] as any)[key] || fallback || key;
  };

  const openPartnerForm = (type: 'doctor' | 'hospital' | 'clinic' | 'api') => {
    setPartnerFormToOpen(type);
  };

  const addToCart = (item: CartItem) => {
    setCart(prev => {
      const existing = prev.find(i => i.id === item.id);
      if (existing) {
        return prev.map(i => i.id === item.id ? { ...i, quantity: i.quantity + item.quantity } : i);
      }
      return [...prev, item];
    });
  };

  const removeFromCart = (id: string) => {
    setCart(prev => prev.filter(i => i.id !== id));
  };

  const clearCart = () => setCart([]);

  return (
    <AppContext.Provider value={{ 
      language, 
      setLanguage, 
      theme, 
      toggleTheme, 
      t, 
      openPartnerForm, 
      partnerFormToOpen, 
      setPartnerFormToOpen,
      cart,
      addToCart,
      removeFromCart,
      clearCart
    }}>
      {children}
    </AppContext.Provider>
  );
};

export const useAppContext = () => {
  const context = useContext(AppContext);
  if (!context) throw new Error('useAppContext must be used within an AppProvider');
  return context;
};
