import { Hospital, Doctor, Specialty, DiagnosticCenter } from './types';

export const DIAGNOSTIC_CENTERS: DiagnosticCenter[] = [
  {
    id: 'dc1',
    name: 'Pioneer Diagnostic Center',
    category: 'Imaging',
    description: 'Large diagnostic imaging center offering MRI, CT, X-ray, ultrasound, mammography & more across multiple locations.',
    services: ['MRI', 'CT', 'X-ray', 'Ultrasound', 'Mammography'],
    location: 'Bole, Addis Ababa',
    rating: 4.8
  },
  {
    id: 'dc2',
    name: 'Dr. Alia Diagnostic Center',
    category: 'Imaging',
    description: 'Advanced imaging services including MRI, CT-scan, Ultrasound, Digital X-ray and echo.',
    services: ['MRI', 'CT-scan', 'Ultrasound', 'Digital X-ray', 'Echo'],
    location: 'Kazanchis, Addis Ababa',
    rating: 4.7
  },
  {
    id: 'dc3',
    name: 'Wudassie Diagnostic Center',
    category: 'Imaging',
    description: 'Diagnostic imaging including CT scan, X-ray & ultrasound with 24/7 services.',
    services: ['CT scan', 'X-ray', 'Ultrasound'],
    location: 'Piazza, Addis Ababa',
    rating: 4.6
  },
  {
    id: 'dc4',
    name: 'Bright Diagnostic Imaging Center',
    category: 'Imaging',
    description: 'Highly rated imaging services in Addis Ababa.',
    services: ['Imaging', 'X-ray', 'Ultrasound'],
    location: 'Bole, Addis Ababa',
    rating: 4.9
  },
  {
    id: 'dc5',
    name: 'BMY Diagnostic Center',
    category: 'General',
    description: 'Diagnostic center offering various tests.',
    services: ['General Tests', 'Diagnostics'],
    location: 'Mexico, Addis Ababa',
    rating: 4.4
  },
  {
    id: 'dc6',
    name: 'Manna Diagnostic Center',
    category: 'Imaging',
    description: 'Well-reviewed imaging and diagnostic services.',
    services: ['Imaging', 'Diagnostics'],
    location: 'Sarbet, Addis Ababa',
    rating: 4.5
  },
  {
    id: 'dc7',
    name: 'Swiss Diagnostics Ethiopia',
    category: 'Laboratory',
    description: 'Laboratory services with advanced testing and pathology capabilities.',
    services: ['Advanced Testing', 'Pathology'],
    location: 'Bole, Addis Ababa',
    rating: 4.9
  },
  {
    id: 'dc8',
    name: 'ONCO Pathology Diagnostic Center',
    category: 'Laboratory',
    description: 'Focus on pathology, hematology, clinical chemistry and cancer diagnostics.',
    services: ['Pathology', 'Hematology', 'Clinical Chemistry', 'Cancer Diagnostics'],
    location: 'Enkulal Fabrica, Addis Ababa',
    rating: 4.8
  },
  {
    id: 'dc9',
    name: 'Abel Radiological Diagnostic Center',
    category: 'Radiology',
    description: 'Radiology and related diagnostics services.',
    services: ['Radiology', 'Diagnostics'],
    location: 'Addis Ababa',
    rating: 4.3
  },
  {
    id: 'dc10',
    name: 'Hema Advanced Diagnostic Laboratory',
    category: 'Laboratory',
    description: 'Laboratory center offering various medical tests.',
    services: ['Medical Tests', 'Advanced Lab'],
    location: 'Addis Ababa',
    rating: 4.7
  },
  {
    id: 'dc11',
    name: 'Viva Diagnostic Center',
    category: 'General',
    description: 'General diagnostic center.',
    services: ['General Diagnostics'],
    location: 'Addis Ababa',
    rating: 4.2
  },
  {
    id: 'dc12',
    name: 'Ethio Canada Diagnostic Center',
    category: 'General',
    description: 'Diagnostic services linked with a hospital department.',
    services: ['Hospital Diagnostics'],
    location: 'Addis Ababa',
    rating: 4.5
  }
];

export const HOSPITALS: Hospital[] = [
  {
    id: 'h1',
    name: "St. Paul's Hospital Millennium Medical College",
    type: 'Public',
    rating: 4.2,
    services: ['Emergency', 'Surgery', 'Maternity', 'Pediatrics', 'Internal Medicine'],
    workingHours: '24/7',
    emergency: true,
    location: 'Gullele, Addis Ababa',
    phone: '+251 11 275 0125',
    description: 'A leading public referral hospital and medical college in Ethiopia, providing specialized care and medical education.',
    image: 'https://image2url.com/r2/default/images/1774713013690-dd494c57-c9fd-40b1-85c7-c6865deaad5d.jpg'
  },
  {
    id: 'h2',
    name: 'Tikur Anbessa Specialized Hospital (Black Lion)',
    type: 'Public',
    rating: 4.0,
    services: ['Oncology', 'Cardiology', 'Neurology', 'Specialized Surgery'],
    workingHours: '24/7',
    emergency: true,
    location: 'Lideta, Addis Ababa',
    phone: '+251 11 551 1211',
    description: 'The largest specialized referral hospital in Ethiopia, serving as the main teaching hospital for Addis Ababa University.',
    image: 'https://image2url.com/r2/default/images/1774713058884-847413c2-81ac-47c9-ab0e-51e77ed03a44.jpg'
  },
  {
    id: 'h3',
    name: 'ICMC General Hospital',
    type: 'Private',
    rating: 4.8,
    services: ['Diagnostics', 'General Surgery', 'Internal Medicine', 'Physiotherapy'],
    workingHours: '24/7',
    emergency: true,
    location: 'CMC Road, Addis Ababa',
    phone: '+251 11 646 0100',
    description: 'A premium private hospital known for its high-quality diagnostic services and patient-centered care.',
    image: 'https://image2url.com/r2/default/images/1774711952467-4a343d4f-9f8b-4949-af4b-273daa2c2eaa.webp'
  },
  {
    id: 'h4',
    name: 'Lancet General Hospital',
    type: 'Private',
    rating: 4.7,
    services: ['Cardiology', 'Gastroenterology', 'Urology', 'Emergency'],
    workingHours: '24/7',
    emergency: true,
    location: 'Megenagna, Addis Ababa',
    phone: '+251 11 661 0101',
    description: 'Modern healthcare facility with state-of-the-art medical equipment and highly qualified specialists.',
    image: 'https://image2url.com/r2/default/images/1774712126834-db2fd696-6a7d-4935-886b-508145a5b923.jpg'
  },
  {
    id: 'h5',
    name: 'Myung Sung Christian Medical Center (Korean Hospital)',
    type: 'Private',
    rating: 4.9,
    services: ['Advanced Surgery', 'Cardiology', 'Dental', 'Ophthalmology'],
    workingHours: '24/7',
    emergency: true,
    location: 'Gerji, Addis Ababa',
    phone: '+251 11 629 2963',
    description: 'Renowned for its advanced medical technology and international standards of care.',
    image: 'https://image2url.com/r2/default/images/1774712482588-f906f4ee-1d1d-4cd0-bfad-ff3e519787fa.webp'
  },
  {
    id: 'h6',
    name: 'Nordic Medical Centre',
    type: 'Clinic',
    rating: 4.9,
    services: ['Family Medicine', 'Emergency Evacuation', 'Pediatrics', 'Diagnostics'],
    workingHours: '24/7',
    emergency: true,
    location: 'Bole, Addis Ababa',
    phone: '+251 91 120 1201',
    description: 'Expatriate-standard medical facility providing high-quality primary and emergency care.',
    image: 'https://image2url.com/r2/default/images/1774712560135-74a802dd-e454-4739-9017-a3e780679fa1.jpg'
  },
  {
    id: 'h7',
    name: 'Hallelujah General Hospital',
    type: 'Private',
    rating: 4.6,
    services: ['Orthopedics', 'General Medicine', 'Surgery', 'Maternity'],
    workingHours: '24/7',
    emergency: true,
    location: 'Gotera, Addis Ababa',
    phone: '+251 11 442 4646',
    description: 'A modern private hospital offering a wide range of medical services with a focus on patient comfort.',
    image: 'https://image2url.com/r2/default/images/1774711868451-72a71768-ddcb-415a-930b-ecc8652a949e.jpg'
  },
  {
    id: 'h8',
    name: 'Washington Medical Center',
    type: 'Private',
    rating: 4.7,
    services: ['Specialized Diagnostics', 'Internal Medicine', 'Surgery'],
    workingHours: '08:00 - 20:00',
    emergency: false,
    location: 'Bole Atlas, Addis Ababa',
    phone: '+251 11 663 0707',
    description: 'Premium medical center providing specialized diagnostic and treatment services.',
    image: 'https://image2url.com/r2/default/images/1774771859898-0cc17237-ea6d-4fa3-8128-828fe3bc75b9.jpg'
  },
  {
    id: 'h9',
    name: 'Silk Road General Hospital',
    type: 'Private',
    rating: 4.8,
    services: ['Neurosurgery', 'Cardiology', 'Emergency', 'Inpatient Care'],
    workingHours: '24/7',
    emergency: true,
    location: 'Sarbet, Addis Ababa',
    phone: '+251 11 320 6222',
    description: 'A state-of-the-art hospital built with international collaboration, specializing in neurosurgery and cardiology.',
    image: 'https://image2url.com/r2/default/images/1774712976037-8b0bef3f-8e81-4123-bbff-1e552013ddd8.jpg'
  },
  {
    id: 'h10',
    name: 'Zewditu Memorial Hospital',
    type: 'Public',
    rating: 3.9,
    services: ['HIV/AIDS Care', 'Maternity', 'General Surgery', 'Internal Medicine'],
    workingHours: '24/7',
    emergency: true,
    location: 'Filwoha, Addis Ababa',
    phone: '+251 11 551 8085',
    description: 'One of the oldest public hospitals in Addis Ababa, known for its comprehensive HIV/AIDS treatment programs.',
    image: 'https://image2url.com/r2/default/images/1774771937397-bfa5424d-63b2-4b93-ad42-76ba5f1c8b48.jpg'
  },
  {
    id: 'h11',
    name: 'Yekatit 12 Hospital',
    type: 'Public',
    rating: 4.1,
    services: ['Burn Treatment', 'Plastic Surgery', 'Pediatrics', 'Emergency'],
    workingHours: '24/7',
    emergency: true,
    location: '6 Kilo, Addis Ababa',
    phone: '+251 11 155 3033',
    description: 'A public hospital specialized in burn treatment and plastic surgery, alongside general medical services.',
    image: 'https://image2url.com/r2/default/images/1774771901309-76ca21a4-a612-4516-a000-6fb6be022f76.jpg'
  },
  {
    id: 'h12',
    name: 'Landmark General Hospital',
    type: 'Private',
    rating: 4.5,
    services: ['Internal Medicine', 'Surgery', 'Pediatrics', 'Maternity'],
    workingHours: '24/7',
    emergency: true,
    location: 'Mexico, Addis Ababa',
    phone: '+251 11 552 5463',
    description: 'A well-established private hospital providing a broad spectrum of medical and surgical services.',
    image: 'https://image2url.com/r2/default/images/1774712244031-3c265a5e-e674-4f68-84eb-8137c1e6a0af.webp'
  },
  {
    id: 'h13',
    name: 'MeQrez General Hospital',
    type: 'Private',
    rating: 4.4,
    services: ['Internal Medicine', 'Surgery', 'Diagnostics', 'Inpatient Care'],
    workingHours: '24/7',
    emergency: true,
    location: 'Addis Ababa',
    phone: '+251 11 123 4567',
    description: 'A prominent hospital with specialists and subspecialists in many fields, providing advanced patient care.',
    image: 'https://image2url.com/r2/default/images/1774712402473-3f94a08a-36d4-476a-8d73-0327f6d2920c.jpg'
  },
  {
    id: 'h14',
    name: 'Kadisco General Hospital',
    type: 'Private',
    rating: 4.5,
    services: ['Pediatrics', 'Gynecology', 'Orthopedics', 'Emergency'],
    workingHours: '24/7',
    emergency: true,
    location: 'Gerji Roba, Addis Ababa',
    phone: '+251 11 629 8902',
    description: 'Specialized private hospital offering high-quality pediatric, gynecologic and orthopedic care.',
    image: 'https://image2url.com/r2/default/images/1774712036904-2a9d8448-d801-48c4-a130-61cf4e9b0526.jpg'
  },
  {
    id: 'h15',
    name: 'Amin General Hospital',
    type: 'Private',
    rating: 4.6,
    services: ['Gastroenterology', 'Diabetology', 'Internal Medicine', 'Surgery'],
    workingHours: '24/7',
    emergency: true,
    location: 'Addis Ababa',
    phone: '+251 11 551 2345',
    description: 'Respected private hospital with specialists in internal medicine, surgery, and endocrinology.',
    image: 'https://image2url.com/r2/default/images/1774711113200-474ed02a-4599-4cf6-b778-4d0122d84277.jpg'
  },
  {
    id: 'h16',
    name: 'Addis Ababa Fistula Hospital',
    type: 'Public',
    rating: 4.9,
    services: ['Obstetric Fistula Repair', 'Maternity', 'Women Health'],
    workingHours: '08:00 - 17:00',
    emergency: false,
    location: 'Addis Ababa',
    phone: '+251 11 371 3433',
    description: 'World-renowned hospital specializing in the treatment and repair of obstetric fistula injuries.',
    image: 'https://image2url.com/r2/default/images/1774710581093-3800dbc0-a4a3-4794-b1e0-ef1045b5a3e8.webp'
  },
  {
    id: 'h17',
    name: 'Migbare Senay Hospital',
    type: 'Private',
    rating: 4.3,
    services: ['Orthopedics', 'General Medicine', 'Surgery'],
    workingHours: '24/7',
    emergency: true,
    location: 'Addis Ababa',
    phone: '+251 11 122 3344',
    description: 'Private hospital providing specialized orthopedic and general surgical services.',
    image: 'https://image2url.com/r2/default/images/1774773880815-6f76aef1-a4ef-4f18-9dc0-644189340822.jpg'
  },
  {
    id: 'h18',
    name: 'Hayat Hospital',
    type: 'Private',
    rating: 4.5,
    services: ['Emergency', 'Surgery', 'Maternity', 'Pediatrics', 'Internal Medicine'],
    workingHours: '24/7',
    emergency: true,
    location: 'Bole, Addis Ababa',
    phone: '+251 11 661 4250',
    description: 'A well-known private hospital in Addis Ababa providing comprehensive medical services.',
    image: 'https://image2url.com/r2/default/images/1774711908524-2a29d070-9c05-4366-a131-21de0732f5da.jpg'
  },
  {
    id: 'h19',
    name: 'Bethel Teaching General Hospital',
    type: 'Private',
    rating: 4.4,
    services: ['General Medicine', 'Surgery', 'Teaching', 'Emergency'],
    workingHours: '24/7',
    emergency: true,
    location: 'Kolfe Keranio, Addis Ababa',
    phone: '+251 11 348 2222',
    description: 'A teaching hospital providing quality healthcare and medical training.',
    image: 'https://image2url.com/r2/default/images/1774711255541-89bd8d32-be31-417a-bf58-51cf66e2d915.jpg'
  },
  {
    id: 'h20',
    name: 'Addis Hiwot General Hospital',
    type: 'Private',
    rating: 4.6,
    services: ['Internal Medicine', 'Surgery', 'Maternity', 'Diagnostics'],
    workingHours: '24/7',
    emergency: true,
    location: 'Bole, Addis Ababa',
    phone: '+251 11 662 3922',
    description: 'Providing high-quality medical services with a focus on patient safety and comfort.',
    image: 'https://image2url.com/r2/default/images/1774710733211-453dfe43-08e0-441f-9a3a-fc0b38e1349b.jpg'
  },
  {
    id: 'h21',
    name: 'Girum General Hospital',
    type: 'Private',
    rating: 4.7,
    services: ['Cardiology', 'Surgery', 'Emergency', 'Diagnostics'],
    workingHours: '24/7',
    emergency: true,
    location: 'Arada, Addis Ababa',
    phone: '+251 11 122 7474',
    description: 'A modern private hospital with advanced medical facilities and expert staff.',
    image: 'https://image2url.com/r2/default/images/1774711826210-efa06031-1caf-4dba-b144-85363bdd4fe4.jpg'
  },
  {
    id: 'h22',
    name: 'Yerer Hospital',
    type: 'Private',
    rating: 4.3,
    services: ['General Medicine', 'Surgery', 'Maternity'],
    workingHours: '24/7',
    emergency: true,
    location: 'Yerer, Addis Ababa',
    phone: '+251 11 645 4697',
    description: 'Serving the Yerer community with dedicated healthcare services.',
    image: 'https://image2url.com/r2/default/images/1774773819168-dec762fd-d0eb-4c5b-a2dc-31e36ae671ab.jpg'
  },
  {
    id: 'h23',
    name: 'Tirunesh Beijing General Hospital',
    type: 'Public',
    rating: 4.2,
    services: ['Emergency', 'Surgery', 'General Medicine', 'Maternity'],
    workingHours: '24/7',
    emergency: true,
    location: 'Akaki Kality, Addis Ababa',
    phone: '+251 11 434 0505',
    description: 'A public hospital built with international support, providing essential healthcare services.',
    image: 'https://image2url.com/r2/default/images/1774771798079-37e91685-2d2d-48a0-9c5b-9df3c50f8687.png'
  },
  {
    id: 'h24',
    name: 'Minilik II Hospital',
    type: 'Public',
    rating: 4.0,
    services: ['Emergency', 'Surgery', 'Ophthalmology', 'General Medicine'],
    workingHours: '24/7',
    emergency: true,
    location: 'Arada, Addis Ababa',
    phone: '+251 11 123 4272',
    description: 'One of the oldest public hospitals in Ethiopia, specializing in ophthalmology and general care.',
    image: 'https://image2url.com/r2/default/images/1774712361219-c69373da-ced8-4aa3-8727-eeb66b631654.jpg'
  },
  {
    id: 'h25',
    name: 'Ras Desta Damtew Memorial Hospital',
    type: 'Public',
    rating: 4.1,
    services: ['General Medicine', 'Surgery', 'Maternity', 'Emergency'],
    workingHours: '24/7',
    emergency: true,
    location: 'Arada, Addis Ababa',
    phone: '+251 11 155 1211',
    description: 'A public hospital providing a wide range of medical services to the community.',
    image: 'https://image2url.com/r2/default/images/1774712934657-04c72e8f-a4d9-4482-96fd-99d6db56148d.jpg'
  },
  {
    id: 'h26',
    name: 'Alert Hospital',
    type: 'Public',
    rating: 4.4,
    services: ['Dermatology', 'Orthopedics', 'Rehabilitation', 'Surgery'],
    workingHours: '24/7',
    emergency: true,
    location: 'Zenebework, Addis Ababa',
    phone: '+251 11 321 1345',
    description: 'Specialized in dermatology and orthopedics, particularly known for leprosy and TB treatment.',
    image: 'https://image2url.com/r2/default/images/1774711003403-c4fd6cd2-0b34-4a70-8ba5-b61b3ed3a276.jpg'
  },
  {
    id: 'h27',
    name: 'Amanuel Mental Specialized Hospital',
    type: 'Public',
    rating: 4.2,
    services: ['Psychiatry', 'Mental Health', 'Neurology'],
    workingHours: '24/7',
    emergency: true,
    location: 'Addis Ketema, Addis Ababa',
    phone: '+251 11 275 0125',
    description: 'The primary specialized hospital for mental health and psychiatric care in Ethiopia.',
    image: 'https://image2url.com/r2/default/images/1774711065143-f37ef86c-7585-468a-b972-56b86d4792b9.jpg'
  },
  {
    id: 'h28',
    name: 'Ghandi Memorial Hospital',
    type: 'Public',
    rating: 4.3,
    services: ['Maternity', 'Gynecology', 'Pediatrics'],
    workingHours: '24/7',
    emergency: true,
    location: 'Kirkos, Addis Ababa',
    phone: '+251 11 551 8185',
    description: 'Specialized public hospital focusing on maternal and child health.',
    image: 'https://image2url.com/r2/default/images/1774711785335-797038b8-8923-4a93-9191-b13bbe72f7f9.jpg'
  },
  {
    id: 'h29',
    name: 'Armed Forces Referral & Teaching Hospital',
    type: 'Public',
    rating: 4.5,
    services: ['Specialized Surgery', 'Internal Medicine', 'Emergency', 'Teaching'],
    workingHours: '24/7',
    emergency: true,
    location: 'Lideta, Addis Ababa',
    phone: '+251 11 371 1900',
    description: 'A major referral and teaching hospital serving the armed forces and the public.',
    image: 'https://image2url.com/r2/default/images/1774711168771-3c3b5905-6761-40ea-aa06-15cd14c652b9.jpg'
  },
  {
    id: 'h30',
    name: 'Police Hospital',
    type: 'Public',
    rating: 4.2,
    services: ['General Medicine', 'Surgery', 'Emergency'],
    workingHours: '24/7',
    emergency: true,
    location: 'Arada, Addis Ababa',
    phone: '+251 11 551 1211',
    description: 'Providing healthcare services primarily to the police force and their families, as well as the public.',
    image: 'https://image2url.com/r2/default/images/1774712894340-767cb64a-9a8a-48aa-86de-a222f612fa1a.jpg'
  },
  {
    id: 'h31',
    name: 'Federal Police Referral Hospital',
    type: 'Public',
    rating: 4.3,
    services: ['General Medicine', 'Surgery', 'Emergency'],
    workingHours: '24/7',
    emergency: true,
    location: 'Addis Ababa',
    phone: '+251 11 551 1211',
    description: 'Referral hospital for the federal police force providing comprehensive medical care.',
    image: 'https://image2url.com/r2/default/images/1774711743385-b1eb74bc-7f9b-4a99-893e-71ee8ace928d.jpg'
  },
  {
    id: 'h32',
    name: 'Balcha Hospital',
    type: 'Public',
    rating: 4.1,
    services: ['General Medicine', 'Surgery', 'Emergency'],
    workingHours: '24/7',
    emergency: true,
    location: 'Addis Ababa',
    phone: '+251 11 551 3222',
    description: 'A public hospital providing essential medical services to the community.',
    image: 'https://image2url.com/r2/default/images/1774711213848-31b94523-399e-4701-bc38-dfef8083d36c.jpeg'
  },
  {
    id: 'h33',
    name: 'Ethio-Tebib Hospital',
    type: 'Private',
    rating: 4.4,
    services: ['Internal Medicine', 'Surgery', 'Maternity'],
    workingHours: '24/7',
    emergency: true,
    location: 'Addis Ababa',
    phone: '+251 11 552 5656',
    description: 'Private hospital offering a range of medical and surgical services.',
    image: 'https://image2url.com/r2/default/images/1774711676159-23dd7d6c-0b7f-496f-b0e6-ab904bc3b71d.jpg'
  },
  {
    id: 'h34',
    name: 'Tazma Medical Center',
    type: 'Private',
    rating: 4.5,
    services: ['Diagnostics', 'General Medicine', 'Surgery'],
    workingHours: '24/7',
    emergency: true,
    location: 'Bole, Addis Ababa',
    phone: '+251 11 661 5656',
    description: 'A modern medical center providing comprehensive diagnostic and treatment services.',
    image: 'https://image2url.com/r2/default/images/1774771626734-2fa27865-0383-429f-ab4d-880fbbb5639a.webp'
  },
  {
    id: 'h35',
    name: 'Brass Maternal and Child Health Hospital',
    type: 'Private',
    rating: 4.7,
    services: ['Maternity', 'Pediatrics', 'Gynecology'],
    workingHours: '24/7',
    emergency: true,
    location: 'Bole, Addis Ababa',
    phone: '+251 11 662 5656',
    description: 'Specialized hospital focusing on the health of mothers and children.',
    image: 'https://image2url.com/r2/default/images/1774711352371-4faf314d-bcd0-4743-be6e-4e01bac02802.jpg'
  },
  {
    id: 'h36',
    name: 'Bethzatha General Hospital',
    type: 'Private',
    rating: 4.3,
    services: ['General Medicine', 'Surgery', 'Emergency'],
    workingHours: '24/7',
    emergency: true,
    location: 'Stadium, Addis Ababa',
    phone: '+251 11 551 4141',
    description: 'A well-known private hospital providing a variety of medical services.',
    image: 'https://image2url.com/r2/default/images/1774711306995-231712b1-a005-4fc8-8b4a-81b7bffb4744.jpg'
  },
  {
    id: 'h37',
    name: 'Kibru Hospital',
    type: 'Private',
    rating: 4.2,
    services: ['General Medicine', 'Surgery', 'Maternity'],
    workingHours: '24/7',
    emergency: true,
    location: 'Addis Ababa',
    phone: '+251 11 662 5656',
    description: 'Providing dedicated healthcare services to the community.',
    image: 'https://image2url.com/r2/default/images/1774712076581-307870cb-6651-4d9a-a568-72bb1ea7e4c1.jpg'
  }
];

export const DOCTORS: Doctor[] = [
  {
    id: 'd1',
    name: 'Dr. Habtewold Mulat',
    specialty: 'Orthopedic & Trauma Surgeon',
    hospital: 'St. Paul’s / MeQrez / Migbare Senay',
    experience: 12,
    availableTimes: ['Mon 09:00', 'Wed 14:00'],
    image: 'https://picsum.photos/seed/doc_habtewold/400/400',
    rating: 4.9,
    description: 'Dr. Habtewold Mulat is a highly experienced Orthopedic and Trauma Surgeon with over a decade of clinical experience treating complex bone and joint conditions. He completed his medical education at Addis Ababa University and his residency in orthopedic surgery at St. Paul’s Hospital Millennium Medical College. He is certified by the College of Surgeons of East, Central and Southern Africa (COSECSA). Dr. Habtewold’s expertise spans fracture and dislocation management, bone infection treatment, and reconstructive surgeries. He is known for combining technical precision with compassionate patient care and uses modern, minimally invasive techniques when appropriate. He also contributes to orthopedic research and mentors younger surgeons.'
  },
  {
    id: 'd2',
    name: 'Dr. Wubeshet Alemayehu',
    specialty: 'General Surgeon',
    hospital: 'ICMC General Hospital',
    experience: 15,
    availableTimes: ['Tue 10:00', 'Thu 15:00'],
    image: 'https://picsum.photos/seed/doc_wubeshet/400/400',
    rating: 4.8,
    description: 'Dr. Wubeshet Alemayehu serves as the Chief Clinical Officer and a Senior General Surgeon at ICMC General Hospital. He has broad experience in general surgical procedures, managing both elective and emergency cases. His leadership role at the hospital involves overseeing surgical teams, ensuring quality patient care, and mentoring junior doctors. His practice includes abdominal surgery, gallbladder and hernia operations, and wound management.'
  },
  {
    id: 'd3',
    name: 'Dr. Mulualem Alemayehu',
    specialty: 'Internist & Interventional Cardiologist',
    hospital: 'ICMC General Hospital',
    experience: 14,
    availableTimes: ['Mon 11:00', 'Fri 09:00'],
    image: 'https://picsum.photos/seed/doc_mulualem/400/400',
    rating: 4.9,
    description: 'Dr. Mulualem Alemayehu is a consultant in internal medicine with advanced expertise in cardiology, specifically interventional cardiology — a field that focuses on minimally invasive treatments for heart conditions like coronary artery disease. His work includes conducting diagnostic tests, managing chronic cardiovascular diseases, and performing procedures like angioplasty. He plays a central role in the hospital’s cardiovascular care program.'
  },
  {
    id: 'd4',
    name: 'Dr. Shiferaw Negash',
    specialty: 'Obstetrics & Gynecology / Oncologist',
    hospital: 'ICMC General Hospital',
    experience: 18,
    availableTimes: ['Wed 08:00', 'Fri 13:00'],
    image: 'https://picsum.photos/seed/doc_shiferaw/400/400',
    rating: 4.9,
    description: 'Dr. Shiferaw Negash is a specialist in obstetrics, gynecology, and oncology, focusing on women’s reproductive health and cancers affecting the female reproductive system. He manages prenatal care, childbirth, gynecologic surgeries, and cancer screening and treatment plans. Dr. Shiferaw combines medical care with patient counseling and supports long-term follow‑up for complex gynecologic conditions.'
  },
  {
    id: 'd5',
    name: 'Dr. Mulat Taye',
    specialty: 'Urologist & Renal Transplant Surgeon',
    hospital: 'ICMC General Hospital',
    experience: 20,
    availableTimes: ['Tue 09:00', 'Thu 14:00'],
    image: 'https://picsum.photos/seed/doc_mulat_taye/400/400',
    rating: 5.0,
    description: 'Dr. Mulat Taye is a specialized urologist and renal transplant surgeon. His work focuses on the surgical and medical treatment of urological disorders, including kidney stones, prostate conditions, and reconstructive procedures of the urinary tract. As a transplant surgeon, Dr. Mulat is trained to perform kidney transplant evaluations and surgery, contributing to life‑saving treatments for patients with end‑stage renal disease.'
  },
  {
    id: 'd6',
    name: 'Dr. Assefa Kiflu',
    specialty: 'Neurosurgeon',
    hospital: 'ICMC General Hospital',
    experience: 16,
    availableTimes: ['Mon 10:00', 'Wed 15:00'],
    image: 'https://picsum.photos/seed/doc_assefa/400/400',
    rating: 4.8,
    description: 'Dr. Assefa Kiflu is a neurosurgeon who specializes in surgical treatment of the brain, spinal cord, and nervous system disorders. He manages complex conditions such as traumatic brain injury, spinal tumors, and nerve compressions. Neurosurgeons like Dr. Assefa combine highly precise operative techniques with critical decision‑making to treat life‑threatening neurological conditions.'
  },
  {
    id: 'd7',
    name: 'Dr. Biniyam G/medehin',
    specialty: 'Senior Pediatric Surgeon',
    hospital: 'ICMC General Hospital',
    experience: 12,
    availableTimes: ['Tue 11:00', 'Fri 14:00'],
    image: 'https://picsum.photos/seed/doc_biniyam/400/400',
    rating: 4.7,
    description: 'Dr. Biniyam G/medehin specializes in pediatric surgery — surgery for children from infancy to adolescence. This includes congenital anomalies (birth defects), appendectomies, hernia repair, and emergency surgical care for young patients. Pediatric surgeons require special training to provide age‑appropriate anesthesia and surgical care, and Dr. Biniyam brings experience and child‑centered compassion to his practice.'
  },
  {
    id: 'd8',
    name: 'Dr. Adib Yusuf',
    specialty: 'Pediatrician',
    hospital: 'Kadisco General Hospital',
    experience: 10,
    availableTimes: ['Mon 08:00', 'Wed 13:00'],
    image: 'https://picsum.photos/seed/doc_adib/400/400',
    rating: 4.6,
    description: 'Dr. Adib Yusuf is a pediatric doctor who provides medical care to infants, children, and adolescents. He diagnoses and treats illnesses ranging from common infections to chronic conditions like asthma and diabetes in children. Pediatricians like Dr. Adib also provide regular developmental check‑ups, immunization guidance, and family counseling on child health.'
  },
  {
    id: 'd9',
    name: 'Dr. Samia Ibrahim',
    specialty: 'Gynecologist',
    hospital: 'Kadisco General Hospital',
    experience: 11,
    availableTimes: ['Tue 14:00', 'Thu 09:00'],
    image: 'https://picsum.photos/seed/doc_samia/400/400',
    rating: 4.8,
    description: 'Dr. Samia Ibrahim is a specialist in women’s reproductive health. Her practice includes prenatal care, labor and delivery management, gynecologic surgical procedures, and hormone‑related treatments. Gynecologists play a key role in preventive care and early detection of conditions like cervical cancer and endometriosis.'
  },
  {
    id: 'd10',
    name: 'Dr. Mohammed Issa',
    specialty: 'Orthopedic Doctor',
    hospital: 'Kadisco General Hospital',
    experience: 13,
    availableTimes: ['Wed 10:00', 'Fri 15:00'],
    image: 'https://picsum.photos/seed/doc_issa/400/400',
    rating: 4.7,
    description: 'Dr. Mohammed Issa focuses on musculoskeletal system disorders — bones, joints, ligaments, and muscles. He diagnoses and treats trauma fractures, sports injuries, and joint pain. Orthopedic doctors work closely with physical therapists to ensure comprehensive recovery after surgery or injury.'
  },
  {
    id: 'd11',
    name: 'Dr. Mohammed Shukur',
    specialty: 'Internist & Gastroenterohepatologist',
    hospital: 'Amin General Hospital',
    experience: 14,
    availableTimes: ['Mon 09:00', 'Thu 14:00'],
    image: 'https://picsum.photos/seed/doc_shukur/400/400',
    rating: 4.9,
    description: 'Dr. Mohammed Shukur is an internist with a specialized focus in gastroenterology and hepatology — conditions of the digestive system and liver. He trained both in Ethiopia and abroad and is committed to improving digestive health through evidence‑based treatments, including endoscopy and chronic liver disease management.'
  },
  {
    id: 'd12',
    name: 'Dr. Samuel Molla',
    specialty: 'Internist & Diabetologist',
    hospital: 'Amin General Hospital',
    experience: 15,
    availableTimes: ['Tue 10:00', 'Fri 09:00'],
    image: 'https://picsum.photos/seed/doc_samuel_molla/400/400',
    rating: 4.8,
    description: 'Dr. Samuel Molla is an experienced physician specializing in internal medicine with focus on diabetes care. He combines clinical practice with patient education to manage chronic metabolic disorders and prevent complications. His international training enhances his approach to individualized patient care.'
  },
  {
    id: 'd13',
    name: 'Dr. Burhan Feki',
    specialty: 'Gynecologist & Obstetrician',
    hospital: 'Amin General Hospital',
    experience: 12,
    availableTimes: ['Wed 11:00', 'Sat 10:00'],
    image: 'https://picsum.photos/seed/doc_burhan/400/400',
    rating: 4.7,
    description: 'Dr. Burhan Feki provides comprehensive women’s health services, from prenatal care and childbirth support to gynecologic surgery and family planning. Obstetricians help ensure safe pregnancies and deliveries while addressing reproductive health needs at every life stage.'
  },
  {
    id: 'd14',
    name: 'Mamitu Gashe',
    specialty: 'Obstetric Fistula Surgeon',
    hospital: 'Addis Ababa Fistula Hospital',
    experience: 40,
    availableTimes: ['Mon-Fri 08:00-16:00'],
    image: 'https://picsum.photos/seed/doc_mamitu/400/400',
    rating: 5.0,
    description: 'Mamitu Gashe is one of Ethiopia’s most respected surgeons specializing in obstetric fistula repair — a condition that can occur after prolonged, obstructed labor. She overcame her own fistula experience and was trained by pioneering surgeons to become a leading expert in repairing these injuries. She also trains new surgeons in this delicate surgery and is internationally recognized for her contributions to women’s health.'
  },
  {
    id: 'd15',
    name: 'Dr. Yohannes Tadesse',
    specialty: 'Orthopedic Surgeon',
    hospital: 'Black Lion Hospital',
    experience: 18,
    availableTimes: ['Tue 08:00', 'Thu 13:00'],
    image: 'https://picsum.photos/seed/doc_yohannes/400/400',
    rating: 4.8,
    description: 'Dr. Yohannes is known for his work in orthopedic surgery, treating fractures, joint injuries, and bone disorders. At a major trauma referral hospital like Black Lion, his work includes managing emergency trauma from accidents as well as elective joint and fracture surgeries.'
  },
  {
    id: 'd16',
    name: 'Dr. Solomon Tsegaye',
    specialty: 'Orthopedic Surgeon',
    hospital: 'St. Paul’s Hospital',
    experience: 16,
    availableTimes: ['Wed 09:00', 'Fri 14:00'],
    image: 'https://picsum.photos/seed/doc_solomon/400/400',
    rating: 4.7,
    description: 'Dr. Solomon specializes in bone and joint disorders, trauma care, and reconstruction. He manages complex orthopedic conditions and assists in teaching younger surgeons, which is typical of senior consultants at large academic hospitals.'
  },
  {
    id: 'd17',
    name: 'Dr. Mezgebu Bogale',
    specialty: 'General Surgeon',
    hospital: 'ICMC General Hospital',
    experience: 14,
    availableTimes: ['Mon 10:00', 'Wed 15:00'],
    image: 'https://picsum.photos/seed/doc_mezgebu/400/400',
    rating: 4.6,
    description: 'Dr. Mezgebu operates broadly — from emergency abdominal procedures (like appendectomy) to general soft‑tissue surgery and trauma care.'
  },
  {
    id: 'd18',
    name: 'Dr. Frayol Workeneh',
    specialty: 'Neurologist',
    hospital: 'ICMC General Hospital',
    experience: 10,
    availableTimes: ['Tue 09:00', 'Thu 14:00'],
    image: 'https://picsum.photos/seed/doc_frayol/400/400',
    rating: 4.5,
    description: 'Dr. Frayol diagnoses and manages diseases of the nervous system, including strokes, seizures, and chronic neurological disorders.'
  },
  {
    id: 'd19',
    name: 'Dr. Samson Esseye',
    specialty: 'Senior Surgeon',
    hospital: 'Amin General Hospital',
    experience: 22,
    availableTimes: ['Wed 08:00', 'Fri 13:00'],
    image: 'https://picsum.photos/seed/doc_samson/400/400',
    rating: 4.9,
    description: 'Dr. Samson provides general surgical care. At a hospital like Amin, senior surgeons handle operations related to gallbladder disease, hernia repair, soft‑tissue tumors, and emergency surgical conditions.'
  },
  {
    id: 'd20',
    name: 'Dr. Henok Seife',
    specialty: 'General and Hepatobiliary Surgeon',
    hospital: 'Lancet General Hospital',
    experience: 15,
    availableTimes: ['Mon 09:00', 'Wed 14:00'],
    image: 'https://picsum.photos/seed/doc_henok/400/400',
    rating: 4.9,
    description: 'Dr. Henok leads Lancet Hospital as Chief Executive Officer while practicing as a general surgeon with a subspecialty in hepatobiliary surgery. This means he focuses on surgical diseases of the liver, gallbladder, bile ducts, and pancreas, handling complex abdominal procedures that require precision and deep expertise. He also plays a strategic leadership role in clinical services and hospital development.'
  },
  {
    id: 'd21',
    name: 'Dr. Selamawit Assefa',
    specialty: 'Pediatric Specialist',
    hospital: 'Lancet General Hospital',
    experience: 12,
    availableTimes: ['Tue 10:00', 'Thu 15:00'],
    image: 'https://picsum.photos/seed/doc_selamawit_assefa/400/400',
    rating: 4.8,
    description: 'As Medical Director, Dr. Selamawit oversees clinical quality and patient care systems across the hospital. Her specialty is pediatrics and child health, meaning she diagnoses and manages medical conditions in newborns, infants, children, and adolescents. She ensures pediatric care meets high standards, from routine health checks to managing complex childhood illnesses.'
  },
  {
    id: 'd22',
    name: 'Prof. Berhanu Nega',
    specialty: 'General and Cardiothoracic Surgeon',
    hospital: 'Lancet General Hospital',
    experience: 25,
    availableTimes: ['Wed 08:00', 'Fri 13:00'],
    image: 'https://picsum.photos/seed/doc_berhanu/400/400',
    rating: 5.0,
    description: 'Professor Berhanu is a leading surgeon specializing in cardiothoracic surgery, which includes complex operations on the heart, lungs, esophagus, and chest structures. His role as Vice CEO involves clinical leadership and integrating heart and lung surgical services into Lancet’s broader care framework.'
  },
  {
    id: 'd23',
    name: 'Dr. Mathewos Assefa',
    specialty: 'Internist and Oncologist',
    hospital: 'Lancet General Hospital',
    experience: 18,
    availableTimes: ['Mon 11:00', 'Thu 14:00'],
    image: 'https://picsum.photos/seed/doc_mathewos/400/400',
    rating: 4.9,
    description: 'Dr. Mathewos is trained in internal medicine (treating adult diseases of organs like heart, lungs, kidneys) and oncology (cancer diagnosis and treatment). He manages chronic disease care, cancer diagnostic workflows, chemotherapy planning, and systemic therapy, while also holding a leadership role at the hospital.'
  },
  {
    id: 'd24',
    name: 'Dr. Kibruyisfaw Zewdie',
    specialty: 'Neurosurgeon',
    hospital: 'Lancet General Hospital',
    experience: 16,
    availableTimes: ['Tue 09:00', 'Fri 14:00'],
    image: 'https://picsum.photos/seed/doc_kibruyisfaw/400/400',
    rating: 4.8,
    description: 'Dr. Kibruyisfaw specializes in neurosurgery, focusing on conditions affecting the brain, spinal cord, and nervous system that require surgical intervention. This includes tumors, trauma, spinal disorders, and neurological emergencies. He also helps shape clinical neurosurgical services at Lancet.'
  },
  {
    id: 'd25',
    name: 'Dr. Daniel Ayanaw',
    specialty: 'Specialist',
    hospital: 'MeQrez General Hospital',
    experience: 10,
    availableTimes: ['Mon 08:00', 'Wed 13:00'],
    image: 'https://picsum.photos/seed/doc_daniel/400/400',
    rating: 4.5,
    description: 'Dr. Daniel is one of the physicians listed among MeQrez’s specialists. Although the specific specialty is not detailed online, doctors at MeQrez generally cover internal medicine, diagnostics, and hospital services.'
  },
  {
    id: 'd26',
    name: 'Prof. Mahteme Bekele',
    specialty: 'Senior Consultant',
    hospital: 'MeQrez General Hospital',
    experience: 28,
    availableTimes: ['Tue 10:00', 'Thu 15:00'],
    image: 'https://picsum.photos/seed/doc_mahteme/400/400',
    rating: 4.9,
    description: 'Professor Bekele is listed among leading clinicians at MeQrez, implying significant experience (often academic or senior consultant level) in a major clinical speciality such as internal medicine or a surgical field.'
  },
  {
    id: 'd27',
    name: 'Prof. Engida Abebe',
    specialty: 'Senior Specialist',
    hospital: 'MeQrez General Hospital',
    experience: 26,
    availableTimes: ['Wed 09:00', 'Fri 14:00'],
    image: 'https://picsum.photos/seed/doc_engida/400/400',
    rating: 4.9,
    description: 'Another professor‑level doctor, suggesting a senior specialist role in either medicine or a surgical field. Specialists with “Prof.” titles often are involved in advanced patient care and clinical teaching.'
  },
  {
    id: 'd28',
    name: 'Dr. Yishak Suga',
    specialty: 'Specialist',
    hospital: 'MeQrez General Hospital',
    experience: 12,
    availableTimes: ['Mon 14:00', 'Thu 09:00'],
    image: 'https://picsum.photos/seed/doc_yishak/400/400',
    rating: 4.4,
    description: 'Listed as a doctor at MeQrez, Dr. Yishak contributes to the hospital’s clinical services, potentially in general medicine or a related field based on hospital listings.'
  },
  {
    id: 'd29',
    name: 'Dr. Yemisrach Chanie',
    specialty: 'Specialist',
    hospital: 'MeQrez General Hospital',
    experience: 11,
    availableTimes: ['Tue 11:00', 'Fri 14:00'],
    image: 'https://picsum.photos/seed/doc_yemisrach/400/400',
    rating: 4.5,
    description: 'Dr. Yemisrach is a listed physician. Many doctors at MeQrez work in internal medicine subspecialties, inpatient care, diagnostics and chronic disease management.'
  },
  {
    id: 'd30',
    name: 'Dr. Wubshet Aderaw',
    specialty: 'Specialist',
    hospital: 'MeQrez General Hospital',
    experience: 13,
    availableTimes: ['Wed 10:00', 'Sat 09:00'],
    image: 'https://picsum.photos/seed/doc_wubshet_aderaw/400/400',
    rating: 4.3,
    description: 'Part of the MeQrez medical team, likely involved in clinical care, diagnostics, or inpatient services.'
  },
  {
    id: 'd31',
    name: 'Dr. Wuletaw Chanie',
    specialty: 'Specialist',
    hospital: 'MeQrez General Hospital',
    experience: 14,
    availableTimes: ['Mon 09:00', 'Wed 14:00'],
    image: 'https://picsum.photos/seed/doc_wuletaw/400/400',
    rating: 4.4,
    description: 'Another practicing clinician at MeQrez; the hospital website lists him among doctors available for consultation.'
  },
  {
    id: 'd32',
    name: 'Dr. Workye Tigabie',
    specialty: 'Specialist',
    hospital: 'MeQrez General Hospital',
    experience: 15,
    availableTimes: ['Tue 10:00', 'Thu 15:00'],
    image: 'https://picsum.photos/seed/doc_workye/400/400',
    rating: 4.5,
    description: 'A doctor at MeQrez involved in hospital clinical duties such as patient evaluation and treatment plans.'
  },
  {
    id: 'd33',
    name: 'Dr. Wondwossen Amtataw',
    specialty: 'Specialist',
    hospital: 'MeQrez General Hospital',
    experience: 16,
    availableTimes: ['Wed 08:00', 'Fri 13:00'],
    image: 'https://picsum.photos/seed/doc_wondwossen/400/400',
    rating: 4.6,
    description: 'Also part of MeQrez’s clinical roster, contributing to the hospital’s healthcare services.'
  },
  {
    id: 'd34',
    name: 'Dr. Abel Tesfaye',
    specialty: 'Cardiology',
    hospital: 'Black Lion Hospital',
    experience: 12,
    availableTimes: ['Mon 09:00', 'Wed 14:00'],
    image: 'https://picsum.photos/seed/doc_abel/400/400',
    rating: 4.8,
    description: 'Specialist in interventional cardiology and heart failure management.'
  },
  {
    id: 'd35',
    name: 'Dr. Meron Hailu',
    specialty: 'Cardiology',
    hospital: 'St. Paul’s Hospital',
    experience: 8,
    availableTimes: ['Tue 11:00', 'Thu 16:00'],
    image: 'https://picsum.photos/seed/doc_meron/400/400',
    rating: 4.7,
    description: 'Expert in non-invasive cardiology and echocardiography.'
  },
  {
    id: 'd36',
    name: 'Dr. Elias Kassahun',
    specialty: 'Cardiology',
    hospital: 'MeQrez General Hospital',
    experience: 15,
    availableTimes: ['Wed 10:00', 'Fri 15:00'],
    image: 'https://picsum.photos/seed/doc_elias/400/400',
    rating: 4.9,
    description: 'Senior cardiologist with extensive experience in cardiac rehabilitation.'
  },
  {
    id: 'd37',
    name: 'Dr. Tsion Mulugeta',
    specialty: 'Cardiology',
    hospital: 'Migbare Senay Hospital',
    experience: 10,
    availableTimes: ['Mon 08:00', 'Thu 13:00'],
    image: 'https://picsum.photos/seed/doc_tsion/400/400',
    rating: 4.6,
    description: 'Focused on preventive cardiology and hypertension management.'
  },
  {
    id: 'd38',
    name: 'Dr. Samuel Ayele',
    specialty: 'Cardiology',
    hospital: 'Hayat Hospital',
    experience: 14,
    availableTimes: ['Tue 09:00', 'Fri 14:00'],
    image: 'https://picsum.photos/seed/doc_samuel/400/400',
    rating: 4.8,
    description: 'Specialist in cardiac rhythm disorders and electrophysiology.'
  },
  {
    id: 'd39',
    name: 'Dr. Eden Gebre',
    specialty: 'Neurology',
    hospital: 'Black Lion Hospital',
    experience: 9,
    availableTimes: ['Mon 10:00', 'Wed 15:00'],
    image: 'https://picsum.photos/seed/doc_eden/400/400',
    rating: 4.7,
    description: 'Specialist in epilepsy management and neurophysiology.'
  },
  {
    id: 'd40',
    name: 'Dr. Henok Belay',
    specialty: 'Neurology',
    hospital: 'St. Paul’s Hospital',
    experience: 11,
    availableTimes: ['Tue 08:00', 'Thu 13:00'],
    image: 'https://picsum.photos/seed/doc_henok/400/400',
    rating: 4.8,
    description: 'Expert in stroke treatment and neuro-rehabilitation.'
  },
  {
    id: 'd41',
    name: 'Dr. Rahel Teklu',
    specialty: 'Neurology',
    hospital: 'MeQrez General Hospital',
    experience: 13,
    availableTimes: ['Wed 09:00', 'Fri 14:00'],
    image: 'https://picsum.photos/seed/doc_rahel/400/400',
    rating: 4.9,
    description: 'Specialist in movement disorders and Parkinson’s disease.'
  },
  {
    id: 'd42',
    name: 'Dr. Yared Lemma',
    specialty: 'Neurology',
    hospital: 'Migbare Senay Hospital',
    experience: 7,
    availableTimes: ['Mon 11:00', 'Thu 16:00'],
    image: 'https://picsum.photos/seed/doc_yared/400/400',
    rating: 4.6,
    description: 'Focused on headache disorders and migraine management.'
  },
  {
    id: 'd43',
    name: 'Dr. Tigist Assefa',
    specialty: 'Neurology',
    hospital: 'Hayat Hospital',
    experience: 16,
    availableTimes: ['Tue 10:00', 'Fri 15:00'],
    image: 'https://picsum.photos/seed/doc_tigist/400/400',
    rating: 4.8,
    description: 'Senior neurologist with expertise in multiple sclerosis and neuro-immunology.'
  },
  {
    id: 'd44',
    name: 'Dr. Brook Shimelis',
    specialty: 'Surgery',
    hospital: 'Black Lion Hospital',
    experience: 18,
    availableTimes: ['Mon 08:00', 'Wed 13:00'],
    image: 'https://picsum.photos/seed/doc_brook/400/400',
    rating: 4.9,
    description: 'Senior general surgeon specializing in laparoscopic procedures.'
  },
  {
    id: 'd45',
    name: 'Dr. Kalkidan Teshome',
    specialty: 'Surgery',
    hospital: 'St. Paul’s Hospital',
    experience: 10,
    availableTimes: ['Tue 09:00', 'Thu 14:00'],
    image: 'https://picsum.photos/seed/doc_kalkidan/400/400',
    rating: 4.7,
    description: 'Expert in gastrointestinal surgery and oncology.'
  },
  {
    id: 'd46',
    name: 'Dr. Natnael Girma',
    specialty: 'Surgery',
    hospital: 'MeQrez General Hospital',
    experience: 12,
    availableTimes: ['Wed 10:00', 'Fri 15:00'],
    image: 'https://picsum.photos/seed/doc_natnael/400/400',
    rating: 4.8,
    description: 'Specialist in trauma surgery and emergency surgical care.'
  },
  {
    id: 'd47',
    name: 'Dr. Martha Bekele',
    specialty: 'Surgery',
    hospital: 'Migbare Senay Hospital',
    experience: 14,
    availableTimes: ['Mon 11:00', 'Thu 16:00'],
    image: 'https://picsum.photos/seed/doc_martha/400/400',
    rating: 4.8,
    description: 'Expert in breast surgery and endocrine surgical procedures.'
  },
  {
    id: 'd48',
    name: 'Dr. Solomon Negash',
    specialty: 'Surgery',
    hospital: 'Hayat Hospital',
    experience: 20,
    availableTimes: ['Tue 08:00', 'Fri 13:00'],
    image: 'https://picsum.photos/seed/doc_solomon/400/400',
    rating: 4.9,
    description: 'Renowned surgeon with expertise in complex abdominal surgeries.'
  },
  {
    id: 'd49',
    name: 'Dr. Hiwot Tilahun',
    specialty: 'Pediatrics',
    hospital: 'Black Lion Hospital',
    experience: 11,
    availableTimes: ['Mon 09:00', 'Wed 14:00'],
    image: 'https://picsum.photos/seed/doc_hiwot/400/400',
    rating: 4.8,
    description: 'Specialist in pediatric infectious diseases and vaccinations.'
  },
  {
    id: 'd50',
    name: 'Dr. Mikias Abebe',
    specialty: 'Pediatrics',
    hospital: 'St. Paul’s Hospital',
    experience: 9,
    availableTimes: ['Tue 10:00', 'Thu 15:00'],
    image: 'https://picsum.photos/seed/doc_mikias/400/400',
    rating: 4.7,
    description: 'Expert in pediatric nutrition and growth development.'
  },
  {
    id: 'd51',
    name: 'Dr. Lidya Solomon',
    specialty: 'Pediatrics',
    hospital: 'MeQrez General Hospital',
    experience: 13,
    availableTimes: ['Wed 08:00', 'Fri 13:00'],
    image: 'https://picsum.photos/seed/doc_lidya/400/400',
    rating: 4.9,
    description: 'Specialist in pediatric asthma and allergy management.'
  },
  {
    id: 'd52',
    name: 'Dr. Dawit Kebede',
    specialty: 'Pediatrics',
    hospital: 'Migbare Senay Hospital',
    experience: 15,
    availableTimes: ['Mon 10:00', 'Thu 15:00'],
    image: 'https://picsum.photos/seed/doc_dawit_k/400/400',
    rating: 4.8,
    description: 'Senior pediatrician with expertise in neonatal care.'
  },
  {
    id: 'd53',
    name: 'Dr. Ruth Melaku',
    specialty: 'Pediatrics',
    hospital: 'Hayat Hospital',
    experience: 8,
    availableTimes: ['Tue 11:00', 'Fri 16:00'],
    image: 'https://picsum.photos/seed/doc_ruth/400/400',
    rating: 4.7,
    description: 'Focused on pediatric developmental disorders and behavioral health.'
  },
  {
    id: 'd54',
    name: 'Dr. Abiy Ahmed',
    specialty: 'Gynecology',
    hospital: 'Black Lion Hospital',
    experience: 14,
    availableTimes: ['Mon 10:00', 'Wed 15:00'],
    image: 'https://picsum.photos/seed/doc_abiy/400/400',
    rating: 4.8,
    description: 'Specialist in reproductive endocrinology and infertility.'
  },
  {
    id: 'd55',
    name: 'Dr. Hana Tesfaye',
    specialty: 'Gynecology',
    hospital: 'St. Paul’s Hospital',
    experience: 12,
    availableTimes: ['Tue 08:00', 'Thu 13:00'],
    image: 'https://picsum.photos/seed/doc_hana/400/400',
    rating: 4.9,
    description: 'Expert in high-risk obstetrics and maternal-fetal medicine.'
  },
  {
    id: 'd56',
    name: 'Dr. Zelalem Getachew',
    specialty: 'Gynecology',
    hospital: 'MeQrez General Hospital',
    experience: 10,
    availableTimes: ['Wed 09:00', 'Fri 14:00'],
    image: 'https://picsum.photos/seed/doc_zelalem/400/400',
    rating: 4.7,
    description: 'Specialist in gynecologic oncology and minimally invasive surgery.'
  },
  {
    id: 'd57',
    name: 'Dr. Mekdes Daba',
    specialty: 'Gynecology',
    hospital: 'Migbare Senay Hospital',
    experience: 16,
    availableTimes: ['Mon 11:00', 'Thu 16:00'],
    image: 'https://picsum.photos/seed/doc_mekdes/400/400',
    rating: 4.8,
    description: 'Senior gynecologist with expertise in family planning and reproductive health.'
  },
  {
    id: 'd58',
    name: 'Dr. Fitsum Ayele',
    specialty: 'Gynecology',
    hospital: 'Hayat Hospital',
    experience: 9,
    availableTimes: ['Tue 10:00', 'Fri 15:00'],
    image: 'https://picsum.photos/seed/doc_fitsum/400/400',
    rating: 4.7,
    description: 'Focused on adolescent gynecology and hormonal disorders.'
  },
  {
    id: 'd59',
    name: 'Dr. Anteneh Habte',
    specialty: 'Orthopedics',
    hospital: 'Black Lion Hospital',
    experience: 13,
    availableTimes: ['Mon 08:00', 'Wed 13:00'],
    image: 'https://picsum.photos/seed/doc_anteneh/400/400',
    rating: 4.8,
    description: 'Specialist in joint replacement and arthroscopic surgery.'
  },
  {
    id: 'd60',
    name: 'Dr. Kidist Mulu',
    specialty: 'Orthopedics',
    hospital: 'St. Paul’s Hospital',
    experience: 11,
    availableTimes: ['Tue 09:00', 'Thu 14:00'],
    image: 'https://picsum.photos/seed/doc_kidist/400/400',
    rating: 4.7,
    description: 'Expert in pediatric orthopedics and bone deformity correction.'
  },
  {
    id: 'd61',
    name: 'Dr. Bereket Tekle',
    specialty: 'Orthopedics',
    hospital: 'MeQrez General Hospital',
    experience: 15,
    availableTimes: ['Wed 10:00', 'Fri 15:00'],
    image: 'https://picsum.photos/seed/doc_bereket/400/400',
    rating: 4.9,
    description: 'Specialist in spinal surgery and musculoskeletal trauma.'
  },
  {
    id: 'd62',
    name: 'Dr. Sosina Belay',
    specialty: 'Orthopedics',
    hospital: 'Migbare Senay Hospital',
    experience: 10,
    availableTimes: ['Mon 11:00', 'Thu 16:00'],
    image: 'https://picsum.photos/seed/doc_sosina/400/400',
    rating: 4.6,
    description: 'Focused on hand surgery and upper extremity disorders.'
  },
  {
    id: 'd63',
    name: 'Dr. Henok Teshome',
    specialty: 'Orthopedics',
    hospital: 'Hayat Hospital',
    experience: 14,
    availableTimes: ['Tue 08:00', 'Fri 13:00'],
    image: 'https://picsum.photos/seed/doc_henok_t/400/400',
    rating: 4.8,
    description: 'Specialist in sports medicine and ligament reconstruction.'
  },
  {
    id: 'd64',
    name: 'Dr. Mahlet Girma',
    specialty: 'Dermatology',
    hospital: 'Black Lion Hospital',
    experience: 10,
    availableTimes: ['Mon 09:00', 'Wed 14:00'],
    image: 'https://picsum.photos/seed/doc_mahlet/400/400',
    rating: 4.7,
    description: 'Specialist in medical dermatology and skin cancer screening.'
  },
  {
    id: 'd65',
    name: 'Dr. Surafel Abebe',
    specialty: 'Dermatology',
    hospital: 'St. Paul’s Hospital',
    experience: 8,
    availableTimes: ['Tue 10:00', 'Thu 15:00'],
    image: 'https://picsum.photos/seed/doc_surafel/400/400',
    rating: 4.8,
    description: 'Expert in cosmetic dermatology and laser treatments.'
  },
  {
    id: 'd66',
    name: 'Dr. Meron Tekle',
    specialty: 'Dermatology',
    hospital: 'MeQrez General Hospital',
    experience: 12,
    availableTimes: ['Wed 08:00', 'Fri 13:00'],
    image: 'https://picsum.photos/seed/doc_meron_t/400/400',
    rating: 4.9,
    description: 'Specialist in pediatric dermatology and inflammatory skin diseases.'
  },
  {
    id: 'd67',
    name: 'Dr. Yohannes Bekele',
    specialty: 'Dermatology',
    hospital: 'Migbare Senay Hospital',
    experience: 15,
    availableTimes: ['Mon 10:00', 'Thu 15:00'],
    image: 'https://picsum.photos/seed/doc_yohannes_b/400/400',
    rating: 4.8,
    description: 'Senior dermatologist with expertise in hair and nail disorders.'
  },
  {
    id: 'd68',
    name: 'Dr. Bethlehem Hailu',
    specialty: 'Dermatology',
    hospital: 'Hayat Hospital',
    experience: 9,
    availableTimes: ['Tue 11:00', 'Fri 16:00'],
    image: 'https://picsum.photos/seed/doc_bethlehem_h/400/400',
    rating: 4.7,
    description: 'Focused on dermatopathology and diagnostic skin biopsies.'
  },
  {
    id: 'd69',
    name: 'Dr. Tewodros Kassahun',
    specialty: 'Urology',
    hospital: 'Black Lion Hospital',
    experience: 14,
    availableTimes: ['Mon 10:00', 'Wed 15:00'],
    image: 'https://picsum.photos/seed/doc_tewodros/400/400',
    rating: 4.8,
    description: 'Specialist in urologic oncology and robotic surgery.'
  },
  {
    id: 'd70',
    name: 'Dr. Selam Gebre',
    specialty: 'Urology',
    hospital: 'St. Paul’s Hospital',
    experience: 12,
    availableTimes: ['Tue 08:00', 'Thu 13:00'],
    image: 'https://picsum.photos/seed/doc_selam_g/400/400',
    rating: 4.9,
    description: 'Expert in kidney stone management and endourology.'
  },
  {
    id: 'd71',
    name: 'Dr. Nebiyu Solomon',
    specialty: 'Urology',
    hospital: 'MeQrez General Hospital',
    experience: 10,
    availableTimes: ['Wed 09:00', 'Fri 14:00'],
    image: 'https://picsum.photos/seed/doc_nebiyu/400/400',
    rating: 4.7,
    description: 'Specialist in male infertility and sexual health.'
  },
  {
    id: 'd72',
    name: 'Dr. Martha Tesfaye',
    specialty: 'Urology',
    hospital: 'Migbare Senay Hospital',
    experience: 16,
    availableTimes: ['Mon 11:00', 'Thu 16:00'],
    image: 'https://picsum.photos/seed/doc_martha_t/400/400',
    rating: 4.8,
    description: 'Senior urologist with expertise in female urology and pelvic floor reconstruction.'
  },
  {
    id: 'd73',
    name: 'Dr. Elias Mulugeta',
    specialty: 'Urology',
    hospital: 'Hayat Hospital',
    experience: 9,
    availableTimes: ['Tue 10:00', 'Fri 15:00'],
    image: 'https://picsum.photos/seed/doc_elias_m/400/400',
    rating: 4.7,
    description: 'Focused on pediatric urology and congenital urinary tract anomalies.'
  },
  {
    id: 'd74',
    name: 'Dr. Abel Girma',
    specialty: 'Oncology',
    hospital: 'Black Lion Hospital',
    experience: 13,
    availableTimes: ['Mon 08:00', 'Wed 13:00'],
    image: 'https://picsum.photos/seed/doc_abel_g/400/400',
    rating: 4.8,
    description: 'Specialist in medical oncology and chemotherapy management.'
  },
  {
    id: 'd75',
    name: 'Dr. Rahel Bekele',
    specialty: 'Oncology',
    hospital: 'St. Paul’s Hospital',
    experience: 11,
    availableTimes: ['Tue 09:00', 'Thu 14:00'],
    image: 'https://picsum.photos/seed/doc_rahel_b/400/400',
    rating: 4.7,
    description: 'Expert in radiation oncology and precision radiotherapy.'
  },
  {
    id: 'd76',
    name: 'Dr. Samuel Teshome',
    specialty: 'Oncology',
    hospital: 'MeQrez General Hospital',
    experience: 15,
    availableTimes: ['Wed 10:00', 'Fri 15:00'],
    image: 'https://picsum.photos/seed/doc_samuel_t/400/400',
    rating: 4.9,
    description: 'Specialist in surgical oncology and tumor resection.'
  },
  {
    id: 'd77',
    name: 'Dr. Eden Mulu',
    specialty: 'Oncology',
    hospital: 'Migbare Senay Hospital',
    experience: 10,
    availableTimes: ['Mon 11:00', 'Thu 16:00'],
    image: 'https://picsum.photos/seed/doc_eden_m/400/400',
    rating: 4.6,
    description: 'Focused on breast cancer and gynecologic oncology.'
  },
  {
    id: 'd78',
    name: 'Dr. Henok Ayele',
    specialty: 'Oncology',
    hospital: 'Hayat Hospital',
    experience: 14,
    availableTimes: ['Tue 08:00', 'Fri 13:00'],
    image: 'https://picsum.photos/seed/doc_henok_a/400/400',
    rating: 4.8,
    description: 'Specialist in hematologic oncology and bone marrow transplant.'
  },
  {
    id: 'd79',
    name: 'Dr. Mahlet Tesfaye',
    specialty: 'Gastroenterology',
    hospital: 'Black Lion Hospital',
    experience: 10,
    availableTimes: ['Mon 09:00', 'Wed 14:00'],
    image: 'https://picsum.photos/seed/doc_mahlet_t/400/400',
    rating: 4.7,
    description: 'Specialist in hepatology and liver disease management.'
  },
  {
    id: 'd80',
    name: 'Dr. Surafel Tekle',
    specialty: 'Gastroenterology',
    hospital: 'St. Paul’s Hospital',
    experience: 8,
    availableTimes: ['Tue 10:00', 'Thu 15:00'],
    image: 'https://picsum.photos/seed/doc_surafel_t/400/400',
    rating: 4.8,
    description: 'Expert in therapeutic endoscopy and ERCP.'
  },
  {
    id: 'd81',
    name: 'Dr. Meron Bekele',
    specialty: 'Gastroenterology',
    hospital: 'MeQrez General Hospital',
    experience: 12,
    availableTimes: ['Wed 08:00', 'Fri 13:00'],
    image: 'https://picsum.photos/seed/doc_meron_b/400/400',
    rating: 4.9,
    description: 'Specialist in inflammatory bowel disease (IBD) and Crohn’s disease.'
  },
  {
    id: 'd82',
    name: 'Dr. Yohannes Girma',
    specialty: 'Gastroenterology',
    hospital: 'Migbare Senay Hospital',
    experience: 15,
    availableTimes: ['Mon 10:00', 'Thu 15:00'],
    image: 'https://picsum.photos/seed/doc_yohannes_g/400/400',
    rating: 4.8,
    description: 'Senior gastroenterologist with expertise in digestive motility disorders.'
  },
  {
    id: 'd83',
    name: 'Dr. Bethlehem Abebe',
    specialty: 'Gastroenterology',
    hospital: 'Hayat Hospital',
    experience: 9,
    availableTimes: ['Tue 11:00', 'Fri 16:00'],
    image: 'https://picsum.photos/seed/doc_bethlehem_a/400/400',
    rating: 4.7,
    description: 'Focused on nutritional disorders and malabsorption syndromes.'
  },
  {
    id: 'd84',
    name: 'Dr. Tewodros Solomon',
    specialty: 'Internal Medicine',
    hospital: 'Black Lion Hospital',
    experience: 14,
    availableTimes: ['Mon 10:00', 'Wed 15:00'],
    image: 'https://picsum.photos/seed/doc_tewodros_s/400/400',
    rating: 4.8,
    description: 'Specialist in infectious diseases and tropical medicine.'
  },
  {
    id: 'd85',
    name: 'Dr. Selam Bekele',
    specialty: 'Internal Medicine',
    hospital: 'St. Paul’s Hospital',
    experience: 12,
    availableTimes: ['Tue 08:00', 'Thu 13:00'],
    image: 'https://picsum.photos/seed/doc_selam_b/400/400',
    rating: 4.9,
    description: 'Expert in endocrinology and diabetes management.'
  },
  {
    id: 'd86',
    name: 'Dr. Nebiyu Tesfaye',
    specialty: 'Internal Medicine',
    hospital: 'MeQrez General Hospital',
    experience: 10,
    availableTimes: ['Wed 09:00', 'Fri 14:00'],
    image: 'https://picsum.photos/seed/doc_nebiyu_t/400/400',
    rating: 4.7,
    description: 'Specialist in nephrology and chronic kidney disease.'
  },
  {
    id: 'd87',
    name: 'Dr. Martha Girma',
    specialty: 'Internal Medicine',
    hospital: 'Migbare Senay Hospital',
    experience: 16,
    availableTimes: ['Mon 11:00', 'Thu 16:00'],
    image: 'https://picsum.photos/seed/doc_martha_g/400/400',
    rating: 4.8,
    description: 'Senior internist with expertise in rheumatology and autoimmune diseases.'
  },
  {
    id: 'd88',
    name: 'Dr. Elias Abebe',
    specialty: 'Internal Medicine',
    hospital: 'Hayat Hospital',
    experience: 9,
    availableTimes: ['Tue 10:00', 'Fri 15:00'],
    image: 'https://picsum.photos/seed/doc_elias_a/400/400',
    rating: 4.7,
    description: 'Focused on pulmonology and respiratory health management.'
  },
  {
    id: 'd89',
    name: 'Dr. Mesfin Tekle',
    specialty: 'Dermatology',
    hospital: 'Black Lion Hospital',
    experience: 11,
    availableTimes: ['Mon 08:00', 'Wed 13:00'],
    image: 'https://picsum.photos/seed/doc_mesfin/400/400',
    rating: 4.8,
    description: 'Expert in surgical dermatology and mole removal.'
  },
  {
    id: 'd90',
    name: 'Dr. Kalkidan Bekele',
    specialty: 'Dermatology',
    hospital: 'St. Paul’s Hospital',
    experience: 7,
    availableTimes: ['Tue 09:00', 'Thu 14:00'],
    image: 'https://picsum.photos/seed/doc_kalkidan_b/400/400',
    rating: 4.7,
    description: 'Specialist in pediatric dermatology and eczema management.'
  },
  {
    id: 'd91',
    name: 'Dr. Natnael Tesfaye',
    specialty: 'Dermatology',
    hospital: 'MeQrez General Hospital',
    experience: 13,
    availableTimes: ['Wed 10:00', 'Fri 15:00'],
    image: 'https://picsum.photos/seed/doc_natnael_t/400/400',
    rating: 4.9,
    description: 'Expert in psoriasis treatment and biological therapies.'
  },
  {
    id: 'd92',
    name: 'Dr. Martha Abebe',
    specialty: 'Dermatology',
    hospital: 'Migbare Senay Hospital',
    experience: 14,
    availableTimes: ['Mon 11:00', 'Thu 16:00'],
    image: 'https://picsum.photos/seed/doc_martha_a/400/400',
    rating: 4.8,
    description: 'Specialist in autoimmune skin diseases and blistering disorders.'
  },
  {
    id: 'd93',
    name: 'Dr. Solomon Girma',
    specialty: 'Urology',
    hospital: 'Black Lion Hospital',
    experience: 15,
    availableTimes: ['Mon 09:00', 'Wed 14:00'],
    image: 'https://picsum.photos/seed/doc_solomon_g/400/400',
    rating: 4.8,
    description: 'Expert in laparoscopic urology and minimally invasive stone surgery.'
  },
  {
    id: 'd94',
    name: 'Dr. Hiwot Bekele',
    specialty: 'Urology',
    hospital: 'St. Paul’s Hospital',
    experience: 10,
    availableTimes: ['Tue 10:00', 'Thu 15:00'],
    image: 'https://picsum.photos/seed/doc_hiwot_b/400/400',
    rating: 4.7,
    description: 'Specialist in female urology and voiding dysfunction.'
  },
  {
    id: 'd95',
    name: 'Dr. Mikias Tesfaye',
    specialty: 'Urology',
    hospital: 'MeQrez General Hospital',
    experience: 12,
    availableTimes: ['Wed 08:00', 'Fri 13:00'],
    image: 'https://picsum.photos/seed/doc_mikias_t/400/400',
    rating: 4.9,
    description: 'Expert in reconstructive urology and urethral stricture disease.'
  },
  {
    id: 'd96',
    name: 'Dr. Lidya Girma',
    specialty: 'Urology',
    hospital: 'Migbare Senay Hospital',
    experience: 13,
    availableTimes: ['Mon 10:00', 'Thu 15:00'],
    image: 'https://picsum.photos/seed/doc_lidya_g/400/400',
    rating: 4.8,
    description: 'Specialist in pediatric urology and congenital anomalies.'
  },
  {
    id: 'd97',
    name: 'Dr. Dawit Teshome',
    specialty: 'Urology',
    hospital: 'Hayat Hospital',
    experience: 18,
    availableTimes: ['Tue 11:00', 'Fri 16:00'],
    image: 'https://picsum.photos/seed/doc_dawit_t/400/400',
    rating: 4.7,
    description: 'Senior urologist with expertise in prostate health and men’s wellness.'
  },
  {
    id: 'd98',
    name: 'Dr. Ruth Bekele',
    specialty: 'Oncology',
    hospital: 'Black Lion Hospital',
    experience: 12,
    availableTimes: ['Mon 10:00', 'Wed 15:00'],
    image: 'https://picsum.photos/seed/doc_ruth_b/400/400',
    rating: 4.8,
    description: 'Specialist in gynecologic oncology and ovarian cancer treatment.'
  },
  {
    id: 'd99',
    name: 'Dr. Abiy Tesfaye',
    specialty: 'Oncology',
    hospital: 'St. Paul’s Hospital',
    experience: 14,
    availableTimes: ['Tue 08:00', 'Thu 13:00'],
    image: 'https://picsum.photos/seed/doc_abiy_t/400/400',
    rating: 4.9,
    description: 'Expert in gastrointestinal oncology and colorectal cancer.'
  },
  {
    id: 'd100',
    name: 'Dr. Hana Bekele',
    specialty: 'Oncology',
    hospital: 'MeQrez General Hospital',
    experience: 10,
    availableTimes: ['Wed 09:00', 'Fri 14:00'],
    image: 'https://picsum.photos/seed/doc_hana_b/400/400',
    rating: 4.7,
    description: 'Specialist in lung cancer and thoracic oncology.'
  },
  {
    id: 'd101',
    name: 'Dr. Zelalem Tesfaye',
    specialty: 'Oncology',
    hospital: 'Migbare Senay Hospital',
    experience: 16,
    availableTimes: ['Mon 11:00', 'Thu 16:00'],
    image: 'https://picsum.photos/seed/doc_zelalem_t/400/400',
    rating: 4.8,
    description: 'Senior oncologist with expertise in palliative care and symptom management.'
  },
  {
    id: 'd102',
    name: 'Dr. Mekdes Tesfaye',
    specialty: 'Oncology',
    hospital: 'Hayat Hospital',
    experience: 9,
    availableTimes: ['Tue 10:00', 'Fri 15:00'],
    image: 'https://picsum.photos/seed/doc_mekdes_t/400/400',
    rating: 4.7,
    description: 'Focused on pediatric oncology and childhood leukemia.'
  },
  {
    id: 'd103',
    name: 'Dr. Fitsum Tesfaye',
    specialty: 'Gastroenterology',
    hospital: 'Black Lion Hospital',
    experience: 13,
    availableTimes: ['Mon 08:00', 'Wed 13:00'],
    image: 'https://picsum.photos/seed/doc_fitsum_t/400/400',
    rating: 4.8,
    description: 'Specialist in pancreaticobiliary diseases and advanced endoscopy.'
  },
  {
    id: 'd104',
    name: 'Dr. Anteneh Tesfaye',
    specialty: 'Gastroenterology',
    hospital: 'St. Paul’s Hospital',
    experience: 11,
    availableTimes: ['Tue 09:00', 'Thu 14:00'],
    image: 'https://picsum.photos/seed/doc_anteneh_t/400/400',
    rating: 4.7,
    description: 'Expert in inflammatory bowel disease and clinical nutrition.'
  },
  {
    id: 'd105',
    name: 'Dr. Kidist Tesfaye',
    specialty: 'Gastroenterology',
    hospital: 'MeQrez General Hospital',
    experience: 15,
    availableTimes: ['Wed 10:00', 'Fri 15:00'],
    image: 'https://picsum.photos/seed/doc_kidist_t/400/400',
    rating: 4.9,
    description: 'Specialist in hepatology and liver transplantation medicine.'
  },
  {
    id: 'd106',
    name: 'Dr. Bereket Tesfaye',
    specialty: 'Gastroenterology',
    hospital: 'Migbare Senay Hospital',
    experience: 10,
    availableTimes: ['Mon 11:00', 'Thu 16:00'],
    image: 'https://picsum.photos/seed/doc_bereket_t/400/400',
    rating: 4.6,
    description: 'Focused on functional gastrointestinal disorders and IBS.'
  },
  {
    id: 'd107',
    name: 'Dr. Sosina Tesfaye',
    specialty: 'Gastroenterology',
    hospital: 'Hayat Hospital',
    experience: 14,
    availableTimes: ['Tue 08:00', 'Fri 13:00'],
    image: 'https://picsum.photos/seed/doc_sosina_t/400/400',
    rating: 4.8,
    description: 'Specialist in pediatric gastroenterology and food allergies.'
  },
  {
    id: 'd108',
    name: 'Dr. Henok Tesfaye',
    specialty: 'Internal Medicine',
    hospital: 'Black Lion Hospital',
    experience: 10,
    availableTimes: ['Mon 09:00', 'Wed 14:00'],
    image: 'https://picsum.photos/seed/doc_henok_te/400/400',
    rating: 4.7,
    description: 'Specialist in geriatric medicine and chronic disease management.'
  },
  {
    id: 'd109',
    name: 'Dr. Mahlet Bekele',
    specialty: 'Internal Medicine',
    hospital: 'St. Paul’s Hospital',
    experience: 8,
    availableTimes: ['Tue 10:00', 'Thu 15:00'],
    image: 'https://picsum.photos/seed/doc_mahlet_b/400/400',
    rating: 4.8,
    description: 'Expert in hematology and blood disorders.'
  },
  {
    id: 'd110',
    name: 'Dr. Surafel Bekele',
    specialty: 'Internal Medicine',
    hospital: 'MeQrez General Hospital',
    experience: 12,
    availableTimes: ['Wed 08:00', 'Fri 13:00'],
    image: 'https://picsum.photos/seed/doc_surafel_b/400/400',
    rating: 4.9,
    description: 'Specialist in clinical immunology and allergy.'
  },
  {
    id: 'd111',
    name: 'Dr. Meron Girma',
    specialty: 'Internal Medicine',
    hospital: 'Migbare Senay Hospital',
    experience: 15,
    availableTimes: ['Mon 10:00', 'Thu 15:00'],
    image: 'https://picsum.photos/seed/doc_meron_g/400/400',
    rating: 4.8,
    description: 'Senior internist with expertise in cardiovascular risk assessment.'
  },
  {
    id: 'd112',
    name: 'Dr. Yohannes Abebe',
    specialty: 'Internal Medicine',
    hospital: 'Hayat Hospital',
    experience: 9,
    availableTimes: ['Tue 11:00', 'Fri 16:00'],
    image: 'https://picsum.photos/seed/doc_yohannes_a/400/400',
    rating: 4.7,
    description: 'Focused on metabolic disorders and obesity management.'
  }
];

export const SPECIALTIES: Specialty[] = [
  { id: 's1', name: 'Cardiology', icon: 'Heart', description: 'Heart and vascular health' },
  { id: 's2', name: 'Neurology', icon: 'Brain', description: 'Brain and nervous system' },
  { id: 's3', name: 'Surgery', icon: 'Stethoscope', description: 'Advanced surgical procedures' },
  { id: 's4', name: 'Pediatrics', icon: 'Baby', description: 'Children health care' },
  { id: 's5', name: 'Gynecology', icon: 'User', description: 'Womens health' },
  { id: 's6', name: 'Orthopedics', icon: 'Activity', description: 'Bone and joint health' },
  { id: 's7', name: 'Dermatology', icon: 'Sun', description: 'Skin and hair care' },
  { id: 's8', name: 'Urology', icon: 'Activity', description: 'Urinary tract and kidney health' },
  { id: 's9', name: 'Oncology', icon: 'Activity', description: 'Cancer diagnosis and treatment' },
  { id: 's10', name: 'Gastroenterology', icon: 'Activity', description: 'Digestive system health' },
  { id: 's11', name: 'Internal Medicine', icon: 'Activity', description: 'Adult internal organ health' }
];
